
## The History of Probability {#sec-1-1}

*The use of probability to measure uncertainty and variability dates back hundreds of years. Probability has found application in areas as diverse as medicine, gambling, weather forecasting, and the law.*

The concepts of chance and uncertainty are as old as civilization itself. People have always had to cope with uncertainty about the weather, their food supply, and other aspects of their environment, and have striven to reduce this uncertainty and its effects. Even the idea of gambling has a long history. By about the year 3500 BC, games of chance played with bone objects that could be considered precursors of dice were apparently highly developed in Egypt and elsewhere. Cubical dice with markings virtually identical to those on modern dice have been found in Egyptian tombs dating from 2000 BC. We know that gambling with dice has been popular ever since that time and played an important part in the early development of probability theory.

It is generally believed that the mathematical theory of probability was started by the French mathematicians Blaise Pascal (1623–1662) and Pierre Fermat (1601–1665)
when they succeeded in deriving exact probabilities for certain gambling problems
involving dice. Some of the problems that they solved had been outstanding for about
300 years. However, numerical probabilities of various dice combinations had been
calculated previously by Girolamo Cardano (1501–1576) and Galileo Galilei (1564-1642).

The theory of probability has been developed steadily since the seventeenth
century and has been widely applied in diverse fields of study. Today, probability
theory is an important tool in most areas of engineering, science, and management.
Many research workers are actively engaged in the discovery and establishment of
new applications of probability in fields such as medicine, meteorology, photography
from satellites, marketing, earthquake prediction, human behavior, the design of
computer systems, finance, genetics, and law. In many legal proceedings involving
antitrust violations or employment discrimination, both sides will present probability
and statistical calculations to help support their cases.

### References {.unnumbered}

The ancient history of gambling and the origins of the mathematical theory of probability
are discussed by David (1988), Ore (1960), Stigler (1986), and Todhunter (1865).

Some introductory books on probability theory, which discuss many of the same
topics that will be studied in this book, are Feller (1968); Hoel, Port, and Stone (1971);
Meyer (1970); and Olkin, Gleser, and Derman (1980). Other introductory books,
which discuss both probability theory and statistics at about the same level as they
will be discussed in this book, are Brunk (1975); Devore (1999); Fraser (1976); Hogg
and Tanis (1997); Kempthorne and Folks (1971); Larsen and Marx (2001); Larson
(1974); Lindgren (1976); Miller and Miller (1999); Mood, Graybill, and Boes (1974);
Rice (1995); and Wackerly, Mendenhall, and Schaeffer (2008).