
## Supplementary Exercises {#sec-1-12}

::: {#exr-1-12-1}

# Exercise 1.12.1

1. Suppose that a coin is tossed seven times. Let A denote
the event that a head is obtained on the first toss, and let B
denote the event that a head is obtained on the fifth toss.
Are A and B disjoint?

:::

2. If A, B, and D are three events such that Pr(A ∪ B ∪
D) = 0.7, what is the value of Pr(Ac ∩ Bc ∩ Dc)?
3. Suppose that a certain precinct contains 350 voters, of
which 250 are Democrats and 100 are Republicans. If 30
voters are chosen at random from the precinct, what is the
probability that exactly 18 Democrats will be selected?
4. Suppose that in a deck of 20 cards, each card has one
of the numbers 1, 2, 3, 4, or 5 and there are four cards
with each number. If 10 cards are chosen from the deck at
random, without replacement, what is the probability that
each of the numbers 1, 2, 3, 4, and 5 will appear exactly
twice?
5. Consider the contractor in Example 1.5.4 on page 19.
He wishes to compute the probability that the total utility
demand is high, meaning that the sum of water and electrical
demand (in the units of Example 1.4.5) is at least
54 Chapter 1 Introduction to Probability
215. Draw a picture of this event on a graph like Fig. 1.5
or Fig. 1.9 and find its probability.
6. Suppose that a box contains r red balls and w white
balls. Suppose also that balls are drawn from the box one
at a time, at random, without replacement. (a)What is the
probability that all r red balls will be obtained before any
white balls are obtained? (b) What is the probability that
all r red balls will be obtained before two white balls are
obtained?
7. Suppose that a box contains r red balls, w white balls,
and b blue balls. Suppose also that balls are drawn from
the box one at a time, at random, without replacement.
What is the probability that all r red balls will be obtained
before any white balls are obtained?
8. Suppose that 10 cards, of which seven are red and three
are green, are put at random into 10 envelopes, of which
seven are red and three are green, so that each envelope
contains one card. Determine the probability that exactly
k envelopes will contain a card with a matching color
(k = 0, 1, . . . , 10).
9. Suppose that 10 cards, of which five are red and five
are green, are put at random into 10 envelopes, of which
seven are red and three are green, so that each envelope
contains one card. Determine the probability that exactly
k envelopes will contain a card with a matching color
(k = 0, 1, . . . , 10).
10. Suppose that the events A and B are disjoint. Under
what conditions are Ac and Bc disjoint?
11. LetA1,A2, andA3 be three arbitrary events. Show that
the probability that exactly one of these three events will
occur is
Pr(A1) + Pr(A2) + Pr(A3)
− 2 Pr(A1 ∩ A2) − 2 Pr(A1 ∩ A3) − 2 Pr(A2 ∩ A3)
+ 3 Pr(A1 ∩ A2 ∩ A3).
12. Let A1, . . . , An be n arbitrary events. Show that the
probability that exactly one of these n events will occur is
 n
i=1
Pr(Ai) − 2
 
i<j
Pr(Ai
∩ Aj ) + 3
 
i<j<k
Pr(Ai
∩ Aj
∩ Ak)
− . . . + (−1)n+1n Pr(A1 ∩ A2 . . . ∩ An).

::: {#exr-1-12-13}

# Exercise 1.12.13

Consider a state lottery game in which each winning combination and each ticket consists of one set of $k$ numbers chosen from the numbers $1$ to $n$ without replacement. We shall compute the probability that the winning combination contains at least one pair of consecutive numbers.

(a) Prove that if $n < 2k − 1$, then every winning combination has at least one pair of consecutive numbers. For the rest of the problem, assume that $n \geq 2k − 1$.
(b) Let $i_1 < \cdots < i_k$ be an arbitrary possible winning combination arranged in order from smallest to largest. For $s = 1, \ldots, k$, let $j_s = i_s - (s-1)$. That is,
    $$
    \begin{align*}
    j_1 &= i_1, \\
    j_2 &= i_2 - 1 \\
    &\vdots \\
    j_k &= i_k - (k-1).
    \end{align*}
    $$
    
    Prove that $(i_1, \ldots, i_k)$ contains at least one pair of consecutive numbers if and only if $(j_1, \ldots, j_k)$ contains repeated numbers.
(c) Prove that $1 \leq j_1 \leq \cdots \leq j_k \leq n - k + 1$ and that the number of $(j_1, \ldots, j_k)$ sets with no repeats is $\binom{n-k+1}{k}$.
(d) Find the probability that there is no pair of consecutive numbers in the winning combination.
(e) Find the probability of at least one pair of consecutive numbers in the winning combination.

:::
