
## Supplementary Exercises

1. Suppose that X and Y are independent random variables,
that X has the uniform distribution on the integers
1, 2, 3, 4, 5 (discrete), and that Y has the uniform distribution
on the interval [0, 5] (continuous). Let Z be a random
variable such that Z = X with probability 1/2 and Z = Y
with probability 1/2. Sketch the c.d.f. of Z.
2. Suppose that X and Y are independent random variables.
Suppose that X has a discrete distribution concentrated
on finitely many distinct values with p.f. f1. Suppose
that Y has a continuous distribution with p.d.f. f2. Let
Z = X + Y . Show that Z has a continuous distribution and
find its p.d.f. Hint: First find the conditional p.d.f. ofZ given
X = x.
3. Suppose that the random variable X has the following
c.d.f.:
F(x) =
⎧⎪⎪⎪⎪⎨
⎪⎪⎪⎪⎩
0 for x ≤ 0,
2
5x for 0 < x ≤ 1,
3
5x − 1
5 for 1< x ≤ 2,
1 for x >2.
Verify thatX has a continuous distribution, and determine
the p.d.f. of X.

4. Suppose that the random variable X has a continuous
distribution with the following p.d.f.:
f (x) = 1
2
e
−|x| for −∞< x <∞.
Determine the value x0 such that F(x0) = 0.9, where F(x)
is the c.d.f. of X.
5. Suppose that X1 and X2 are i.i.d. random variables,
and that each has the uniform distribution on the interval
[0, 1]. Evaluate Pr(X2
1
+ X2
2
≤ 1).
6. For each value of p >1, let
c(p) =
∞ 
x=1
1
xp
.
Suppose that the random variable X has a discrete distribution
with the following p.f.:
f (x) = 1
c(p)xp
for x = 1, 2, . . . .
a. For each fixed positive integer n, determine the probability
that X will be divisible by n.
b. Determine the probability that X will be odd.
7. Suppose that X1 and X2 are i.i.d. random variables,
each of which has the p.f. f (x) specified in Exercise 6.
Determine the probability that X1 + X2 will be even.
8. Suppose that an electronic system comprises four components,
and letXj denote the time until component j fails
to operate (j = 1, 2, 3, 4). Suppose that X1, X2, X3, and X4
are i.i.d. random variables, each of which has a continuous
distribution with c.d.f. F(x). Suppose that the system will
operate as long as both component 1 and at least one of
the other three components operate. Determine the c.d.f.
of the time until the system fails to operate.
9. Suppose that a box contains a large number of tacks
and that the probability X that a particular tack will land
with its point up when it is tossed varies from tack to tack
in accordance with the following p.d.f.:
f (x) =
 
2(1− x) for 0 < x <1,
0 otherwise.
Suppose that a tack is selected at random from the box
and that this tack is then tossed three times independently.
Determine the probability that the tack will land with its
point up on all three tosses.
10. Suppose that the radius X of a circle is a random
variable having the following p.d.f.:
f (x) =
 
1
8 (3x + 1) for 0 < x <2,
0 otherwise.
Determine the p.d.f. of the area of the circle.
11. Suppose that the random variable X has the following
p.d.f.:
f (x) =
 
2e
−2x for x >0,
0 otherwise.
Construct a random variable Y = r(X) that has the uniform
distribution on the interval [0, 5].
12. Suppose that the 12 random variablesX1, . . . , X12 are
i.i.d. and each has the uniform distribution on the interval
[0, 20]. For j = 0, 1, . . . , 19, let Ij denote the interval (j ,
j + 1). Determine the probability that none of the 20 disjoint
intervals Ij will contain more than one of the random
variables X1, . . . , X12.
13. Suppose that the joint distribution of X and Y is uniform
over a set A in the xy-plane. For which of the following
sets A are X and Y independent?
a. A circle with a radius of 1 and with its center at the
origin
b. A circle with a radius of 1 and with its center at the
point (3, 5)
c. A square with vertices at the four points (1, 1),
(1, −1), (−1, −1), and (−1, 1)
d. A rectangle with vertices at the four points (0, 0),
(0, 3), (1, 3), and (1, 0)
e. Asquare with vertices at the four points (0, 0), (1, 1),
(0, 2), and (−1, 1)
14. Suppose that X and Y are independent random variables
with the following p.d.f.’s:
f1(x) =
 
1 for 0 < x <1,
0 otherwise,
f2(y) =
 
8y for 0 < y < 1
2 ,
0 otherwise.
Determine the value of Pr(X > Y ).
15. Suppose that, on a particular day, two persons A and
B arrive at a certain store independently of each other.
Suppose that A remains in the store for 15 minutes and B
remains in the store for 10 minutes. If the time of arrival
of each person has the uniform distribution over the hour
between 9:00 a.m. and 10:00 a.m., what is the probability
that A and B will be in the store at the same time?
16. Suppose that X and Y have the following joint p.d.f.:
f (x, y) =
 
2(x + y) for 0 < x < y <1,
0 otherwise.
Determine (a) Pr(X < 1/2); (b) the marginal p.d.f. of X;
and (c) the conditional p.d.f. of Y given that X = x.
204 Chapter 3 Random Variables and Distributions
17. Suppose that X and Y are random variables. The marginal
p.d.f. of X is
f (x) =
 
3x2 for 0 < x <1,
0 otherwise.
Also, the conditional p.d.f. of Y given that X = x is
g(y|x) =
 
3y2
x3 for 0 < y < x,
0 otherwise.
Determine (a) the marginal p.d.f. of Y and (b) the conditional
p.d.f. of X given that Y = y.
18. Suppose that the joint distribution of X and Y is uniform
over the region in the xy-plane bounded by the four
lines x =−1, x = 1, y = x + 1, and y = x − 1. Determine
(a) Pr(XY > 0) and (b) the conditional p.d.f. of Y given
that X = x.
19. Suppose that the random variables X, Y , and Z have
the following joint p.d.f.:
f (x, y, z) =
 
6 for 0 < x < y < z<1,
0 otherwise.
Determine the univariate marginal p.d.f.’s of X, Y , and Z.
20. Suppose that the random variables X, Y , and Z have
the following joint p.d.f.:
f (x, y, z) =
 
2 for 0 < x < y <1 and 0 < z<1,
0 otherwise.
Evaluate Pr(3X>Y|1< 4Z <2).
21. Suppose that X and Y are i.i.d. random variables, and
that each has the following p.d.f.:
f (x) =
 
e
−x for x >0,
0 otherwise.
Also, let U = X/(X + Y) and V = X + Y .
a. Determine the joint p.d.f. of U and V .
b. Are U and V independent?
22. Suppose that the random variables X and Y have the
following joint p.d.f.:
f (x, y) =
 
8xy for 0 ≤ x ≤ y ≤ 1,
0 otherwise.
Also, let U = X/Y and V = Y .
a. Determine the joint p.d.f. of U and V .
b. Are X and Y independent?
c. Are U and V independent?
23. Suppose that X1, . . . ,Xn are i.i.d. random variables,
each having the following c.d.f.:
F(x) =
 
0 for x ≤ 0,
1− e
−x for x >0.
Let Y1= min{X1, . . . ,Xn
} and Yn
= max{X1, . . . ,Xn
}. Determine
the conditional p.d.f. of Y1 given that Yn
= yn.
24. Suppose that X1, X2, and X3 form a random sample of
three observations from a distribution having the following
p.d.f.:
f (x) =
 
2x for 0 < x <1,
0 otherwise.
Determine the p.d.f. of the range of the sample.
25. In this exercise, we shall provide an approximate justification
for Eq. (3.6.6). First, remember that if a and b
are close together, then
  b
a
r(t)dt ≈ (b − a)r


a + b
2
 
. (3.11.1)
Throughout this problem, assume that X and Y have joint
p.d.f. f .
a. Use (3.11.1) to approximate Pr(y −   < Y ≤ y +  ).
b. Use (3.11.1) with r(t) = f (s, t) for fixed s to approximate
Pr(X ≤ x and y −   < Y ≤ y +  )
=
  x
−∞
  y+ 
y− 
f (s, t) dt ds.
c. Show that the ratio of the approximation in part (b)
to the approximation in part (a) is
  x
−∞ g1(s|y) ds.
26. LetX1, X2 be two independent random variables each
with p.d.f. f1(x) = e
−x forx >0 and f1(x) = 0 for x ≤ 0. Let
Z = X1 − X2 and W = X1/X2.
a. Find the joint p.d.f. of X1 and Z.
b. Prove that the conditional p.d.f. of X1 given Z = 0 is
g1(x1|0) =
 
2e
−2x1 for x1 > 0,
0 otherwise.
c. Find the joint p.d.f. of X1 and W.
d. Prove that the conditional p.d.f. of X1 given W = 1 is
h1(x1|1) =
 
4x1e
−2x1 for x1 > 0,
0 otherwise.
e. Notice that {Z = 0} = {W = 1}, but the conditional
distribution of X1 given Z = 0 is not the same as the
conditional distribution of X1 given W = 1. This discrepancy
is known as the Borel paradox. In light
of the discussion that begins on page 146 about
how conditional p.d.f.’s are not like conditioning on
events of probability 0, show how “Z very close to
0” is not the same as “W very close to 1.” Hint: Draw
a set of axes for x1 and x2, and draw the two sets
{(x1, x2) : |x1 − x2| <  } and {(x1, x2) : |x1/x2 − 1| <  }
and see how much different they are.

27. Three boys A, B, and C are playing table tennis. In
each game, two of the boys play against each other and
the third boy does not play. The winner of any given game
n plays again in game n + 1 against the boy who did not
play in game n, and the loser of game n does not play in
game n + 1. The probability that A will beat B in any game
that they play against each other is 0.3, the probability that
A will beat C is 0.6, and the probability that B will beat
C is 0.8. Represent this process as a Markov chain with
stationary transition probabilities by defining the possible
states and constructing the transition matrix.
28. Consider again the Markov chain described in Exercise
27. (a) Determine the probability that the two boys
who play against each other in the first game will play
against each other again in the fourth game. (b) Show that
this probability does not depend on which two boys play
in the first game.

::: {#exr-3-11-29}

# Exercise 3.11.29

Find the unique stationary distribution for the Markov chain in @exr-3-11-27.

:::
