

## Markov Chains {#sec-3-10}

*A popular model for systems that change over time in a random manner is the Markov chain model. A Markov chain is a sequence of random variables, one for each time. At each time, the corresponding random variable gives the state of the system. Also, the conditional distribution of each future state given the past states and the present state depends only on the present state.*

### Stochastic Processes

Example
3.10.1
Occupied Telephone Lines. Suppose that a certain business office has five telephone
lines and that any number of these lines may be in use at any given time. During
a certain period of time, the telephone lines are observed at regular intervals of 2
minutes and the number of lines that are being used at each time is noted. Let X1
denote the number of lines that are being used when the lines are first observed at the
beginning of the period; let X2 denote the number of lines that are being used when
they are observed the second time, 2 minutes later; and in general, for n = 1, 2, . . . ,
let Xn denote the number of lines that are being used when they are observed for the
nth time.  

Definition
3.10.1
Stochastic Process. A sequence of random variables X1, X2, . . . is called a stochastic
process or random process with discrete time parameter. The first random variable X1
is called the initial state of the process; and for n = 2, 3, . . . , the random variable Xn
is called the state of the process at time n.
In Example 3.10.1, the state of the process at any time is the number of lines
being used at that time. Therefore, each state must be an integer between 0 and 5.
Each of the random variables in a stochastic process has a marginal distribution,
and the entire process has a joint distribution. For convenience, in this text, we will
discuss only joint distributions for finitely many of X1, X2, . . . at a time. The meaning
of the phrase “discrete time parameter” is that the process, such as the numbers of
occupied phone lines, is observed only at discrete or separated points in time, rather
than continuously in time. In Sec. 5.4, we will introduce a different stochastic process
(called the Poisson process) with a continuous time parameter.
In a stochastic process with a discrete time parameter, the state of the process
varies in a random manner from time to time. To describe a complete probability
model for a particular process, it is necessary to specify the distribution for the
initial state X1 and also to specify for each n = 1, 2, . . . the conditional distribution
of the subsequent state Xn+1 given X1, . . . , Xn. These conditional distributions are
equivalent to the collection of conditional c.d.f.’s of the following form:
Pr(Xn+1 ≤ b|X1 = x1, X2 = x2, . . . , Xn
= xn).

### Markov Chains

A Markov chain is a special type of stochastic process, defined in terms of the
conditional distributions of future states given the present and past states.


::: {.callout-tip appearance="default" icon=false title="Definition 3.10.2: Markov Chain (DeGroot and Schervish, pp. 188-189)"}

A stochastic process with discrete time parameter is a *Markov chain* if, for each time $n$, the conditional distributions of all $X_{n+j}$ for $j \geq 1$ given $X_1, \ldots, X_n$ depend only on $X_n$ and not on the earlier states $X_1, \ldots X_{n-1}$. In symbols, for $n = 1, 2, \ldots$ and for each $b$ and each possible sequence of states $x_1, x_2, \ldots, x_n$,

$$
Pr(X_{n+1} \leq b \mid X_1 = x_1, X_2 = x_2, \ldots, X_n = x_n) = Pr(X_{n+1} \leq b \mid X_n = x_n).
$$

A Markov chain is called *finite* if there are only finitely many possible states.

:::

Definition
3.10.2
Markov Chain. A stochastic process with discrete time parameter is a Markov chain
if, for each time n, the conditional distributions of all Xn+j for j ≥ 1 givenX1, . . . , Xn
depend only on Xn and not on the earlier states X1, . . . , Xn−1. In symbols, for
3.10 Markov Chains 189
n = 1, 2, . . . and for each b and each possible sequence of states x1, x2, . . . , xn,
Pr(Xn+1 ≤ b|X1 = x1, X2 = x2, . . . , Xn
= xn) = Pr(Xn+1 ≤ b|Xn
= xn).
A Markov chain is called finite if there are only finitely many possible states.
In the remainder of this section, we shall consider only finite Markov chains. This
assumption could be relaxed at the cost of more complicated theory and calculation.
For convenience, we shall reserve the symbol k to stand for the number of possible
states of a general finite Markov chain for the remainder of the section. It will also
be convenient, when discussing a general finite Markov chain, to name the k states
using the integers 1, . . . , k. That is, for each n and j , Xn
= j will mean that the chain
is in state j at time n. In specific examples, it may prove more convenient to label the
states in a more informative fashion. For example, if the states are the numbers of
phone lines in use at given times (as in the example that introduced this section), we
would label the states 0, . . . , 5 even though k = 6.
The following result follows from the multiplication rule for conditional probabilities,
Theorem 2.1.2.
Theorem
3.10.1
For a finite Markov chain, the joint p.f. for the first n states equals
Pr (X1 = x1, X2 = x2, . . . , Xn
= xn)
= Pr(X1 = x1) Pr(X2 = x2|X1 = x1) Pr(X3 = x3|X2 = x2) . . .
Pr(Xn
= xn
|Xn−1 = xn−1). (3.10.1)
Also, for each n and eachm>0,
Pr (Xn+1 = xn+1, Xn+2 = xn+2, . . . , Xn+m
= xn+m
|Xn
= xn)
= Pr(Xn+1 = xn+1|Xn
= xn) Pr(Xn+2 = xn+2|Xn+1 = xn+1)
. . . Pr(Xn+m
= xn+m
|Xn+m−1 = xn+m−1). (3.10.2)
Eq. (3.10.1) is a discrete version of a generalization of conditioning in sequence that
was illustrated in Example 3.7.18 with continuous random variables. Eq. (3.10.2) is a
conditional version of (3.10.1) shifted forward in time.

::: {.callout-tip title="Example 3.10.2: Shopping for Toothpaste (DeGroot and Schervish)"}

In Exercise 4 in Sec. 2.1, we considered a shopper who
chooses between two brands of toothpaste on several occasions. Let Xi
= 1 if the
shopper chooses brand A on the ith purchase, and let Xi
= 2 if the shopper chooses
brand B on the ith purchase. Then the sequence of states X1, X2, . . . is a stochastic
process with two possible states at each time. The probabilities of purchase were
specified by saying that the shopper will choose the same brand as on the previous
purchase with probability 1/3 and will switch with probability 2/3. Since this happens
regardless of purchases that are older than the previous one, we see that this
stochastic process is a Markov chain with
Pr(Xn+1 = 1|Xn
= 1) = 1
3
, Pr(Xn+1 = 2|Xn
= 1) = 2
3
,
Pr(Xn+1 = 1|Xn
= 2) = 2
3
, Pr(Xn+1 = 2|Xn
= 2) = 1
3
.  

:::

Exammple 3.10.2 has an additional feature that puts it in a special class of Markov
chains. The probability of moving from one state at time n to another state at time
n + 1 does not depend on n.
190 Chapter 3 Random Variables and Distributions
Definition
3.10.3
Transition Distributions/Stationary Transition Distributions. Consider a finite Markov
chain with k possible states. The conditional distributions of the state at time n + 1
given the state at time n, that is, Pr(Xn+1 = j |Xn
= i) for i, j = 1, . . . , k and n =
1, 2, . . ., are called the transition distributions of the Markov chain. If the transition
distribution is the same for every time n (n = 1, 2, . . .), then the Markov chain has
stationary transition distributions.
When a Markov chain with k possible states has stationary transition distributions,
there exist probabilities pij for i, j = 1, . . . , k such that, for all n,
Pr(Xn+1 = j |Xn
= i) = pij for n = 1, 2, . . . . (3.10.3)
The Markov chain in Example 3.10.2 has stationary transition distributions. For
example, p11 = 1/3.
In the language of multivariate distributions, when a Markov chain has stationary
transition distributions, specified by (3.10.3), we can write the conditional p.f. of Xn+1
given Xn as
g(j|i) = pij , (3.10.4)
for all n, i, j .

::: {.callout-tip title="Example 3.10.3: Occupied Telephone Lines (DeGroot and Schervish, p. 190)"}

To illustrate the application of these concepts, we shall
consider again the example involving the office with five telephone lines. In order
for this stochastic process to be a Markov chain, the specified distribution for the
number of lines that may be in use at each time must depend only on the number
of lines that were in use when the process was observed most recently 2 minutes
earlier and must not depend on any other observed values previously obtained. For
example, if three lines were in use at time n, then the distribution for time n + 1 must
be the same regardless of whether 0, 1, 2, 3, 4, or 5 lines were in use at time n − 1.
In reality, however, the observation at time n − 1 might provide some information in
regard to the length of time for which each of the three lines in use at time n had been
occupied, and this information might be helpful in determining the distribution for
time n + 1. Nevertheless, we shall suppose now that this process is a Markov chain.
If this Markov chain is to have stationary transition distributions, it must be true that
the rates at which incoming and outgoing telephone calls are made and the average
duration of these telephone calls do not change during the entire period covered
by the process. This requirement means that the overall period cannot include busy
times when more calls are expected or quiet times when fewer calls are expected. For
example, if only one line is in use at a particular observation time, regardless of when
this time occurs during the entire period covered by the process, then there must be
a specific probability p1j that exactly j lines will be in use 2 minutes later.  

:::

### The Transition Matrix

::: {.callout-tip title="Example 3.10.4: Shopping for Toothpaste (DeGroot and Schervish, p. 190)"}
Example
3.10.4
Shopping for Toothpaste. The notation for stationary transition distributions, pij ,
suggests that they could be arranged in a matrix. The transition probabilities for
Example 3.10.2 can be arranged into the following matrix:
P =
  1
3
2
3
2
3
1
3
 
.

:::


Every finite Markov chain with stationary transition distributions has a matrix like
the one constructed in Example 3.10.4.

::: {.callout-tip title="Definition 3.10.4: Transition Matrix (DeGroot and Schervish, p. 191)"}

Consider a finite Markov chain with stationary transition distributions
given by pij
= Pr(Xn+1 = j |Xn
= i) for all n, i, j. The transition matrix of the
Markov chain is defined to be the k × k matrix P with elements pij . That is,
P =
⎡
⎢⎢⎢⎣
p11 . . . p1k
p21 . . . p2k
...
. . .
...
pk1 . . . pkk
⎤
⎥⎥⎥⎦
. (3.10.5)

:::

A transition matrix has several properties that are apparent from its defintion.
For example, each element is nonnegative because all elements are probabilities.
Since each row of a transition matrix is a conditional p.f. for the next state given
some value of the current state, we have
 k
j=1 pij
= 1 for i = 1, . . . , k. Indeed, row
i of the transition matrix specifies the conditional p.f. g(.|i) defined in (3.10.4).
Definition
3.10.5
Stochastic Matrix. A square matrix for which all elements are nonnegative and the
sum of the elements in each row is 1 is called a stochastic matrix.
It is clear that the transition matrix P for every finite Markov chain with stationary
transition probabilities must be a stochastic matrix. Conversely, every k ×k stochastic
matrix can serve as the transition matrix of a finite Markov chain with k possible states
and stationary transition distributions.
Example
3.10.5
A Transition Matrix for the Number of Occupied Telephone Lines. Suppose that in the
example involving the office with five telephone lines, the numbers of lines being
used at times 1, 2, . . . form a Markov chain with stationary transition distributions.
This chain has six possible states 0, 1, . . . , 5, where i is the state in which exactly
i lines are being used at a given time (i = 0, 1, . . . , 5). Suppose that the transition
matrix P is as follows:
P =
⎡
⎢⎢⎢⎢⎢⎢⎢⎢⎣
0 1 2 3 4 5
0 0.1 0.4 0.2 0.1 0.1 0.1
1 0.2 0.3 0.2 0.1 0.1 0.1
2 0.1 0.2 0.3 0.2 0.1 0.1
3 0.1 0.1 0.2 0.3 0.2 0.1
4 0.1 0.1 0.1 0.2 0.3 0.2
5 0.1 0.1 0.1 0.1 0.4 0.2
⎤
⎥⎥⎥⎥⎥⎥⎥⎥⎦
. (3.10.6)
(a) Assuming that all five lines are in use at a certain observation time, we shall
determine the probability that exactly four lines will be in use at the next observation
time. (b) Assuming that no lines are in use at a certain time, we shall determine the
probability that at least one line will be in use at the next observation time.
(a) This probability is the element in the matrix P in the row corresponding to the
state 5 and the column corresponding to the state 4. Its value is seen to be 0.4.
(b) If no lines are in use at a certain time, then the element in the upper left corner
of the matrix P gives the probability that no lines will be in use at the next
observation time. Its value is seen to be 0.1. Therefore, the probability that at
least one line will be in use at the next observation time is 1− 0.1= 0.9.  
192 Chapter 3 Random Variables and Distributions
Figure 3.28 The generation
following {Aa, Aa}.
A a A a
AA aA Aa aa
Example
3.10.6
Plant Breeding Experiment. A botanist is studying a certain variety of plant that is
monoecious (has male and female organs in separate flowers on a single plant).
She begins with two plants I and II and cross-pollinates them by crossing male I
with female II and female I with male II to produce two offspring for the next
generation. The original plants are destroyed and the process is repeated as soon
as the new generation of two plants is mature. Several replications of the study are
run simultaneously. The botanist might be interested in the proportion of plants in
any generation that have each of several possible genotypes for a particular gene.
(See Example 1.6.4 on page 23.) Suppose that the gene has two alleles, A and a.
The genotype of an individual will be one of the three combinations AA, Aa, or aa.
When a new individual is born, it gets one of the two alleles (with probability 1/2
each) from one of the parents, and it independently gets one of the two alleles from
the other parent. The two offspring get their genotypes independently of each other.
For example, if the parents have genotypes AA and Aa, then an offspring will get
A for sure from the first parent and will get either A or a from the second parent
with probability 1/2 each. Let the states of this population be the set of genotypes of
the two members of the current population.We will not distinguish the set {AA, Aa}
from {Aa, AA}. There are then six states: {AA, AA}, {AA, Aa}, {AA, aa}, {Aa, Aa},
{Aa, aa}, and {aa, aa}. For each state, we can calculate the probability that the next
generation will be in each of the six states. For example, if the state is either {AA, AA}
or {aa, aa}, the next generation will be in the same state with probability 1. If the state
is {AA, aa}, the next generation will be in state {Aa, Aa} with probability 1. The other
three states have more complicated transitions.
If the current state is {Aa, Aa}, then all six states are possible for the next generation.
In order to compute the transition distribution, it helps to first compute the
probability that a given offspring will have each of the three genotypes. Figure 3.28
illustrates the possible offspring in this state. Each arrow going down in Fig. 3.28
is a possible inheritance of an allele, and each combination of arrows terminating
in a genotype has probability 1/4. It follows that the probability of AA and aa are
both 1/4, while the probability of Aa is 1/2, because two different combinations of
arrows lead to this offspring. In order for the next state to be {AA, AA}, both offspring
must be AA independently, so the probability of this transition is 1/16. The
same argument implies that the probability of a transition to {aa, aa} is 1/16. A transition
to {AA, Aa} requires one offspring to be AA (probability 1/4) and the other to
be Aa (probabilty 1/2). But the two different genotypes could occur in either order,
so the whole probability of such a transition is 2 × (1/4) × (1/2) = 1/4. A similar argument
shows that a transition to {Aa, aa} also has probability 1/4. A transition to
{AA, aa} requires one offspring to be AA (probability 1/4) and the other to be aa
(probability 1/4). Once again, these can occur in two orders, so the whole probability
is 2 × 1/4 × 1/4 = 1/8. By subtraction, the probability of a transition to {Aa, Aa}
must be 1− 1/16 − 1/16 − 1/4 − 1/4 − 1/8 = 1/4. Here is the entire transition matrix,
which can be verified in a manner similar to what has just been done:
3.10 Markov Chains 193
⎡
⎢⎢⎢⎢⎢⎢⎢⎢⎢⎢⎣
{AA, AA} {AA, Aa} {AA, aa} {Aa, Aa} {Aa, aa} {aa, aa}
{AA, AA} 1.0000 0.0000 0.0000 0.0000 0.0000 0.0000
{AA, Aa} 0.2500 0.5000 0.0000 0.2500 0.0000 0.0000
{AA, aa} 0.0000 0.0000 0.0000 1.0000 0.0000 0.0000
{Aa, Aa} 0.0625 0.2500 0.1250 0.2500 0.2500 0.0625
{Aa, aa} 0.0000 0.0000 0.0000 0.2500 0.5000 0.2500
{aa, aa} 0.0000 0.0000 0.0000 0.0000 0.0000 1.0000
⎤
⎥⎥⎥⎥⎥⎥⎥⎥⎥⎥⎦
.
 
The Transition Matrix for Several Steps
Example
3.10.7
Single Server Queue. Amanager usually checks the server at her store every 5 minutes
to see whether the server is busy or not. She models the state of the server (1= busy
or 2 = not busy) as a Markov chain with two possible states and stationary transition
distributions given by the following matrix:
P =
⎡
⎢⎣
Busy Not busy
Busy 0.9 0.1
Not busy 0.6 0.4
⎤
⎥ ⎦.
The manager realizes that, later in the day, she will have to be away for 10 minutes
and will miss one server check. She wants to compute the conditional distribution of
the state two time periods in the future given each of the possible states. She reasons
as follows: If Xn
= 1 for example, then the state will have to be either 1 or 2 at time
n + 1 even though she does not care now about the state at time n + 1. But, if she
computes the joint conditional distribution of Xn+1 and Xn+2 given Xn
= 1, she can
sum over the possible values of Xn+1 to get the conditional distribution of Xn+2 given
Xn
= 1. In symbols,
Pr(Xn+2 = 1|Xn
= 1) = Pr(Xn+1 = 1, Xn+2 = 1|Xn
= 1)
+ Pr(Xn+1 = 2, Xn+2 = 1|Xn
= 1).
By the second part of Theorem 3.10.1,
Pr(Xn+1 = 1, Xn+2 = 1|Xn
= 1) = Pr(Xn+1 = 1|Xn
= 1) Pr(Xn+2 = 1|Xn+1 = 1)
= 0.9 × 0.9 = 0.81.
Similarly,
Pr(Xn+1 = 2, Xn+2 = 1|Xn
= 1) = Pr(Xn+1 = 2|Xn
= 1) Pr(Xn+2 = 1|Xn+1 = 2)
= 0.1× 0.6 = 0.06.
It follows that Pr(Xn+2 =1|Xn
=1)=0.81+0.06=0.87, and hence Pr(Xn+2 =2|Xn
=
1) = 1− 0.87 = 0.13. By similar reasoning, if Xn
= 2,
Pr(Xn+2 = 1|Xn
= 2) = 0.6 × 0.9 + 0.4 × 0.6 = 0.78,
and Pr(Xn+2 = 2|Xn
= 2) = 1− 0.78 = 0.22.  
Generalizing the calculations in Example 3.10.7 to three or more transitions might
seem tedious. However, if one examines the calculations carefully, one sees a pattern
194 Chapter 3 Random Variables and Distributions
that will allow a compact calculation of transition distributions for several steps.
Consider a general Markov chain with k possible states 1, . . . , k and the transition
matrix P given by Eq. (3.10.5). Assuming that the chain is in state i at a given time n,
we shall now determine the probability that the chain will be in state j at time n + 2.
In other words, we shall determine the conditional probability of Xn+2 = j given
Xn
= i. The notation for this probability is p(2)
ij .
We argue as the manager did in Example 3.10.7. Let r denote the value of Xn+1
that is not of primary interest but is helpful to the calculation. Then
p(2)
ij
= Pr(Xn+2 = j |Xn
= i)
=
 k
r=1
Pr(Xn+1 = r and Xn+2 = j |Xn
= i)
=
 k
r=1
Pr(Xn+1 = r|Xn
= i) Pr(Xn+2 = j |Xn+1 = r, Xn
= i)
=
 k
r=1
Pr(Xn+1 = r|Xn
= i) Pr(Xn+2 = j |Xn+1 = r)
=
 k
r=1
pirprj ,
where the third equality follows from Theorem 2.1.3 and the fourth equality follows
from the definition of a Markov chain.
The value of p(2)
ij can be determined in the following manner: If the transition
matrix P is squared, that is, if the matrix P2 = PP is constructed, then the element in
the ith row and the jth column of the matrix P2 will be
 k
r=1 pirprj . Therefore, p(2)
ij
will be the element in the ith row and the jth column of P2.
By a similar argument, the probability that the chain will move from the state i to
the state j in three steps, or p(3)
ij
= Pr(Xn+3 = j |Xn
= i), can be found by constructing
the matrix P3 = P2P. Then the probability p(3)
ij will be the element in the ith row and
the jth column of the matrix P3.
In general, we have the following result.
Theorem
3.10.2
Multiple Step Transitions. Let P be the transition matrix of a finite Markov chain with
stationary transition distributions. For each m = 2, 3, . . ., the mth power Pm of the
matrix P has in row i and column j the probability p(m)
ij that the chain will move from
state i to state j in m steps.
Definition
3.10.6
Multiple Step Transition Matrix. Under the conditions of Theorem 3.10.2, the matrix
Pm is called the m-step transition matrix of the Markov chain.
In summary, the ith row of the m-step transition matrix gives the conditional distribution
of Xn+m given Xn
= i for all i = 1, . . . , k and all n, m = 1, 2, . . . .
Example
3.10.8
The Two-Step and Three-Step Transition Matrices for the Number of Occupied Telephone
Lines. Consider again the transition matrix P given by Eq. (3.10.6) for the Markov
chain based on five telephone lines. We shall assume first that i lines are in use at a
3.10 Markov Chains 195
certain time, and we shall determine the probability that exactly j lines will be in use
two time periods later.
If we multiply the matrix P by itself, we obtain the following two-step transition
matrix:
P2 =
⎡
⎢⎢⎢⎢⎢⎢⎢⎢⎣
0 1 2 3 4 5
0 0.14 0.23 0.20 0.15 0.16 0.12
1 0.13 0.24 0.20 0.15 0.16 0.12
2 0.12 0.20 0.21 0.18 0.17 0.12
3 0.11 0.17 0.19 0.20 0.20 0.13
4 0.11 0.16 0.16 0.18 0.24 0.15
5 0.11 0.16 0.15 0.17 0.25 0.16
⎤
⎥⎥⎥⎥⎥⎥⎥⎥⎦
. (3.10.7)
From this matrix we can find any two-step transition probability for the chain, such
as the following:
i. If two lines are in use at a certain time, then the probability that four lines will
be in use two time periods later is 0.17.
ii. If three lines are in use at a certain time, then the probability that three lines
will again be in use two time periods later is 0.20.
We shall now assume that i lines are in use at a certain time, and we shall
determine the probability that exactly j lines will be in use three time periods later.
If we construct the matrix P3 = P2P, we obtain the following three-step transition
matrix:
P3 =
⎡
⎢⎢⎢⎢⎢⎢⎢⎢⎣
0 1 2 3 4 5
0 0.123 0.208 0.192 0.166 0.183 0.128
1 0.124 0.207 0.192 0.166 0.183 0.128
2 0.120 0.197 0.192 0.174 0.188 0.129
3 0.117 0.186 0.186 0.179 0.199 0.133
4 0.116 0.181 0.177 0.176 0.211 0.139
5 0.116 0.180 0.174 0.174 0.215 0.141
⎤
⎥⎥⎥⎥⎥⎥⎥⎥⎦
. (3.10.8)
From this matrix we can find any three-step transition probability for the chain, such
as the following:
i. If all five lines are in use at a certain time, then the probability that no lines will
be in use three time periods later is 0.116.
ii. If one line is in use at a certain time, then the probability that exactly one line
will again be in use three time periods later is 0.207.  
Example
3.10.9
Plant Breeding Experiment. In Example 3.10.6, the transition matrix has many zeros,
since many of the transitions will not occur. However, if we are willing to wait two
steps, we will find that the only transitions that cannot occur in two steps are those
from the first state to anything else and those from the last state to anything else.
196 Chapter 3 Random Variables and Distributions
Here is the two-step transition matrix:
⎡
⎢⎢⎢⎢⎢⎢⎢⎢⎢⎢⎣
{AA, AA} {AA, Aa} {AA, aa} {Aa, Aa} {Aa, aa} {aa, aa}
{AA, AA} 1.0000 0.0000 0.0000 0.0000 0.0000 0.0000
{AA, Aa} 0.3906 0.3125 0.0313 0.1875 0.0625 0.0156
{AA, aa} 0.0625 0.2500 0.1250 0.2500 0.2500 0.0625
{Aa, Aa} 0.1406 0.1875 0.0313 0.3125 0.1875 0.1406
{Aa, aa} 0.0156 0.0625 0.0313 0.1875 0.3125 0.3906
{aa, aa} 0.0000 0.0000 0.0000 0.0000 0.0000 1.0000
⎤
⎥⎥⎥⎥⎥⎥⎥⎥⎥⎥⎦
.
Indeed, if we look at the three-step or the four-step or the general m-step transition
matrix, the first and last rows will always be the same.  
The first and last states in Example 3.10.9 have the property that, once the chain gets
into one of those states, it can’t get out. Such states occur in many Markov chains
and have a special name.
Definition
3.10.7
Absorbing State. In a Markov chain, if pii
= 1 for some state i, then that state is called
an absorbing state.
In Example 3.10.9, there is positive probability of getting into each absorbing state
in two steps no matter where the chain starts. Hence, the probability is 1 that the
chain will eventually be absorbed into one of the absorbing states if it is allowed to
run long enough.
The Initial Distribution
Example
3.10.10
Single Server Queue. The manager in Example 3.10.7 enters the store thinking that the
probability is 0.3 that the server will be busy the first time that she checks. Hence, the
probability is 0.7 that the server will be not busy. These values specify the marginal
distribution of the state at time 1, X1.We can represent this distribution by the vector
v = (0.3, 0.7) that gives the probabilities of the two states at time 1 in the same order
that they appear in the transition matrix.  
The vector giving the marginal distribution of X1 in Example 3.10.10 has a special
name.
Definition
3.10.8
Probability Vector/Initial Distribution. A vector consisting of nonnegative numbers
that add to 1 is called a probability vector. A probability vector whose coordinates
specify the probabilities that a Markov chain will be in each of its states at time 1 is
called the initial distribution of the chain or the intial probability vector.
For Example 3.10.2, the initial distribution was given in Exercise 4 in Sec. 2.1 as
v = (0.5, 0.5).
The initial distribution and the transition matrix together determine the entire
joint distribution of the Markov chain. Indeed, Theorem 3.10.1 shows how to construct
the joint distribution of the chain from the initial probability vector and the
transition matrix. Letting v = (v1, . . . , vk) denote the initial distribution, Eq. (3.10.1)
can be rewritten as
Pr(X1 = x1, X2 = x2, . . . , Xn
= xn) = vx1px1x2
. . . pxn−1xn
. (3.10.9)
3.10 Markov Chains 197
The marginal distributions of states at times later than 1 can be found from the
joint distribution.
Theorem
3.10.3
Marginal Distributions at Times Other Than 1. Consider a finite Markov chain with
stationary transition distributions having initial distribution v and transition matrix
P. The marginal distribution of Xn, the state at time n, is given by the probability
vector vPn−1.
Proof The marginal distribution of Xn can be found from Eq. (3.10.9) by summing
over the possible values of x1, . . . , xn−1. That is,
Pr(Xn
= xn) =
 k
xn−1=1
. . .
 k
x2=1
 k
x1=1
vx1px1x2px2x3
. . . pxn−1xn
. (3.10.10)
The innermost sum in Eq. (3.10.10) for x1= 1, . . . , k involves only the first two factors
vx1px1x2 and produces the x2 coordinate of vP. Similarly, the next innermost sum
over x2 = 1, . . . , k involves only the x2 coordinate of vP and px2x3 and produces the
x3 coordinate of vPP = vP 2. Proceeding in this way through all n − 1 summations
produces the xn coordinate of vP n−1.
Example
3.10.11
Probabilities for the Number of Occupied Telephone Lines. Consider again the office
with five telephone lines and the Markov chain for which the transition matrix P is
given by Eq. (3.10.6). Suppose that at the beginning of the observation process at
time n = 1, the probability that no lines will be in use is 0.5, the probability that one
line will be in use is 0.3, and the probability that two lines will be in use is 0.2. Then
the initial probability vector is v = (0.5, 0.3, 0.2, 0, 0, 0).We shall first determine the
distribution of the number of lines in use at time 2, one period later.
By an elementary computation it will be found that
vP = (0.13, 0.33, 0.22, 0.12, 0.10, 0.10).
Since the first component of this probability vector is 0.13, the probability that no
lines will be in use at time 2 is 0.13; since the second component is 0.33, the probability
that exactly one line will be in use at time 2 is 0.33; and so on.
Next, we shall determine the distribution of the number of lines that will be in
use at time 3.
By use of Eq. (3.10.7), it can be found that
vP2 = (0.133, 0.227, 0.202, 0.156, 0.162, 0.120).
Since the first component of this probability vector is 0.133, the probability that
no lines will be in use at time 3 is 0.133; since the second component is 0.227, the
probability that exactly one line will be in use at time 3 is 0.227; and so on.

### Stationary Distributions

::: {.callout-tip title="Example 3.10..12: A Special Initial Distribution for Telephone Lines (DeGroot and Schervish, p. 197)"}

Suppose that the initial distribution
for the number of occupied telephone lines is

$$
v = (0.119, 0.193, 0.186, 0.173, 0.196, 0.133).
$$

It can be shown, by matrix multiplication, that vP = v. This means that if v is the
initial distribution, then it is also the distribution after one transition. Hence, it will
also be the distribution after two or more transitions as well.

:::

::: {.callout-tip title="Definition 3.10.9: Stationary Distribution (DeGroot and Schervish, p. 198)"}

Let P be the transition matrix for a Markov chain. A probability
vector v that satisfies vP = v is called a stationary distribution for the Markov
chain.

:::

The initial distribution in Example 3.10.12 is a stationary distribution for the telephone
lines Markov chain. If the chain starts in this distribution, the distribution stays
the same at all times. Every finite Markov chain with stationary transition distributions
has at least one stationary distribution. Some chains have a unique stationary
distribution.
Note: A Stationary Distribution Does Not Mean That the Chain is Not Moving. It
is important to note that vP n gives the probabilities that the chain is in each of
its states after n transitions, calculated before the initial state of the chain or any
transitions are observed. These are different from the probabilities of being in the
various states after observing the initial state or after observing any of the intervening
transitions. In addition, a stationary distribution does not imply that the Markov
chain is staying put. If a Markov chain starts in a stationary distribution, then for
each state i, the probability that the chain is in state i after n transitions is the same
as the probability that it is state i at the start. But the Markov chain can still move
around from one state to the next at each transition. The one case in which a Markov
chain does stay put is after it moves into an absorbing state. A distribution that is
concentrated solely on absorbing states will necessarily be stationary because the
Markov chain will never move if it starts in such a distribution. In such cases, all of
the uncertainty surrounds the initial state, which will also be the state after every
transition.
Example
3.10.13
Stationary Distributions for the Plant Breeding Experiment. Consider again the experiment
described in Example 3.10.6. The first and sixth states, {AA, AA} and {aa, aa},
respectively, are absorbing states. It is easy to see that every initial distribution of the
form v = (p, 0, 0, 0, 0, 1− p) for 0 ≤ p ≤ 1 has the property that vP = v. Suppose
that the chain is in state 1 with probability p and in state 6 with probability 1− p
at time 1. Because these two states are absorbing states, the chain will never move
and the event X1 = 1 is the same as the event that Xn
= 1 for all n. Similarly, X1 = 6
is the same as Xn
= 6. So, thinking ahead to where the chain is likely to be after n
transitions, we would also say that it will be in state 1 with probability p and in state
6 with probability 1− p.  
Method for Finding Stationary Distributions We can rewrite the equation vP = v
that defines stationary distributions as v[P − I]= 0, where I is a k × k identity matrix
and 0 is a k-dimensional vector of all zeros. Unfortunately, this system of equations
has lots of solutions even if there is a unique stationary distribution. The reason is
that whenever v solves the system, so does cv for all real c (including c = 0). Even
though the system has k equations for k variables, there is at least one redundant
equation. However, there is also one missing equation. We need to require that the
solution vector v has coordinates that sum to 1.We can fix both of these problems by
replacing one of the equations in the original system by the equation that says that
the coordinates of v sum to 1.
To be specific, define the matrix G to be P − I with its last column replaced by
a column of all ones. Then, solve the equation
3.10 Markov Chains 199
vG = (0, . . . , 0, 1). (3.10.11)
If there is a unique stationary distribution, we will find it by solving (3.10.11). In this
case, the matrix G will have an inverse G−1 that satisfies
GG−1 = G−1G = I.
The solution of (3.10.11) will then be
v = (0, . . . , 0, 1)G−1,
which is easily seen to be the bottom row of the matrix G−1. This was the method
used to find the stationary distribution in Example 3.10.12. If the Markov chain
has multiple stationary distributions, then the matrix G will be singular, and this
method will not find any of the stationary distributions. That is what would happen
in Example 3.10.13 if one were to apply the method.
Example
3.10.14
Stationary Distribution for Toothpaste Shopping. Consider the transition matrix P
given in Example 3.10.4. We can construct the matrix G as follows:
P − I =
  −2
3
2
3
2
3
−2
3
 
; hence G =
  −2
3 1
2
3 1
 
.
The inverse of G is
G−1 =
  −3
4
3
4
1
2
1
2
 
.
We now see that the stationary distribution is the bottom row of G
−1, v = (1/2, 1/2).
 
There is a special case in which it is known that a unique stationary distribution
exists and it has special properties.
Theorem
3.10.4
If there exists m such that every element of Pm is strictly positive, then
. the Markov chain has a unique stationary distribution v,
. limn→∞ Pn is a matrix with all rows equal to v, and
. no matter with what distribution the Markov chain starts, its distribution after
n steps converges to v as n→∞.
We shall not prove Theorem 3.10.4, although some evidence for the second
claim can be seen in Eq. (3.10.8), where the six rows of P3 are much more alike
than the rows of P and they are very similar to the stationary distribution given in
Example 3.10.12. The third claim in Theorem 3.10.4 actually follows easily from the
second claim. In Sec. 12.5, we shall introduce a method that makes use of the third
claim in Theorem 3.10.4 in order to approximate distributions of random variables
when those distributions are difficult to calculate exactly.
The transition matrices in Examples 3.10.2, 3.10.5, and 3.10.7 satisfy the conditions
of Theorem 3.10.4. The following example has a unique stationary distribution
but does not satisfy the conditions of Theorem 3.10.4.
Example
3.10.15
Alternating Chain. Let the transition matrix for a two-state Markov chain be
P =
 
0 1
1 0
 
.
200 Chapter 3 Random Variables and Distributions
The matrix G is easy to construct and invert, and we find that the unique stationary
distribution is v = (0.5, 0.5). However, as m increases, Pm alternates between P and
the 2 × 2 identity matrix. It does not converge and never does it have all elements
strictly positive. If the initial distribution is (v1, v2), the distribution after n steps
alternates between (v1, v2) and (v2, v1).  
Another example that fails to satisfy the conditions of Theorem 3.10.4 is the
gambler’s ruin problem from Sec. 2.4.
Example
3.10.16
Gambler’s Ruin. In Sec. 2.4, we described the gambler’s ruin problem, in which a
gambler wins one dollar with probability p and loses one dollar with probability 1− p
on each play of a game. The sequence of amounts held by the gambler through the
course of those plays forms a Markov chain with two absorbing states, namely, 0 and
k. There are k − 1 other states, namely, 1, . . . , k − 1. (This notation violates our use of
k to stand for the number of states, which is k + 1 in this example.We felt this was less
confusing than switching from the original notation of Sec. 2.4.) The transition matrix
has first and last row being (1, 0, . . . , 0) and (0, . . . , 1), respectively. The ith row (for
i = 1, . . . , k − 1) has 0 everywhere except in coordinate i − 1 where it has 1− p and
in coordinate i + 1 where it has p. Unlike Example 3.10.15, this time the sequence
of matrices Pm converges but there is no unique stationary distribution. The limit
of Pm has as its last column the numbers a0, . . . , ak, where ai is the probability that
the fortune of a gambler who starts with i dollars reaches k dollars before it reaches
0 dollars. The first column of the limit has the numbers 1− a0, . . . , 1− ak and the
rest of the limit matrix is all zeros. The stationary distributions have the same form
as those in Example 3.10.13, namely, all probability is in the absorbing states.  
Summary
A Markov chain is a stochastic process, a sequence of random variables giving the
states of the process, in which the conditional distribution of the state at the next
time given all of the past states depends on the past states only through the most
recent state. For Markov chains with finitely many states and stationary transition
distributions, the transitions over time can be described by a matrix giving the probabilities
of transition from the state indexing the row to the state indexing the column
(the transition matrix P). The initial probability vector v gives the distribution of the
state at time 1. The transition matrix and initial probability vector together allow
calculation of all probabilities associated with the Markov chain. In particular, Pn
gives the probabilities of transitions over n time periods, and vP n gives the distribution
of the state at time n + 1. A stationary distribution is a probability vector v
such that vP = v. Every finite Markov chain with stationary transition distributions
has at least one stationary distribution. For many Markov chains, there is a unique
stationary distribution and the distribution of the chain after n transitions converges
to the stationary distribution as n goes to $\infty$.

### Exercises

1. Consider the Markov chain in Example 3.10.2 with initial
probability vector v = (1/2, 1/2).
a. Find the probability vector specifying the probabilities
of the states at time n = 2.
b. Find the two-step transition matrix.
3.10 Markov Chains 201
2. Suppose that the weather can be only sunny or cloudy
and the weather conditions on successive mornings form
a Markov chain with stationary transition probabilities.
Suppose also that the transition matrix is as follows:
Sunny Cloudy
Sunny 0.7 0.3
Cloudy 0.6 0.4
a. If it is cloudy on a given day, what is the probability
that it will also be cloudy the next day?
b. If it is sunny on a given day, what is the probability
that it will be sunny on the next two days?
c. If it is cloudy on a given day, what is the probability
that it will be sunny on at least one of the next three
days?
3. Consider again the Markov chain described in Exercise
2.
a. If it is sunny on a certain Wednesday, what is the
probability that it will be sunny on the following
Saturday?
b. If it is cloudy on a certain Wednesday, what is the
probability that it will be sunny on the following
Saturday?
4. Consider again the conditions of Exercises 2 and 3.
a. If it is sunny on a certain Wednesday, what is the
probability that it will be sunny on both the following
Saturday and Sunday?
b. If it is cloudy on a certain Wednesday, what is the
probability that it will be sunny on both the following
Saturday and Sunday?
5. Consider again the Markov chain described in Exercise
2. Suppose that the probability that it will be sunny
on a certain Wednesday is 0.2 and the probability that it
will be cloudy is 0.8.
a. Determine the probability that it will be cloudy on
the next day, Thursday.
b. Determine the probability that it will be cloudy on
Friday.
c. Determine the probability that it will be cloudy on
Saturday.
6. Suppose that a student will be either on time or late for
a particular class and that the events that he is on time or
late for the class on successive days form a Markov chain
with stationary transition probabilities. Suppose also that
if he is late on a given day, then the probability that he will
be on time the next day is 0.8. Furthermore, if he is on time
on a given day, then the probability that he will be late the
next day is 0.5.
a. If the student is late on a certain day, what is the
probability that he will be on time on each of the next
three days?
b. If the student is on time on a given day, what is the
probability that he will be late on each of the next
three days?
7. Consider again the Markov chain described in Exercise
6.
a. If the student is late on the first day of class, what is
the probability that he will be on time on the fourth
day of class?
b. If the student is on time on the first day of class, what
is the probability that he will be on time on the fourth
day of class?
8. Consider again the conditions of Exercises 6 and 7.
Suppose that the probability that the student will be late
on the first day of class is 0.7 and that the probability that
he will be on time is 0.3.
a. Determine the probability that he will be late on the
second day of class.
b. Determine the probability that he will be on time on
the fourth day of class.
9. Suppose that a Markov chain has four states 1, 2, 3, 4
and stationary transition probabilities as specified by the
following transition matrix:
⎡
⎢⎢⎢⎢⎢⎣
1 2 3 4
1 1/4 1/4 0 1/2
2 0 1 0 0
3 1/2 0 1/2 0
4 1/4 1/4 1/4 1/4
⎤
⎥⎥
⎥⎥⎥⎦
.
a. If the chain is in state 3 at a given time n, what is the
probability that it will be in state 2 at time n + 2?
b. If the chain is in state 1 at a given time n, what is the
probability that it will be in state 3 at time n + 3?
10. Let X1 denote the initial state at time 1 of the Markov
chain for which the transition matrix is as specified in
Exercise 5, and suppose that the initial probabilities are
as follows:
Pr(X1 = 1) = 1/8, Pr(X1 = 2) = 1/4,
Pr(X1 = 3) = 3/8, Pr(X1 = 4) = 1/4.
Determine the probabilities that the chain will be in
states 1, 2, 3, and 4 at time n for each of the following values
of n: (a) n = 2; (b) n = 3; (c) n = 4.
11. Each time that a shopper purchases a tube of toothpaste,
she chooses either brandAor brandB. Suppose that
the probability is 1/3 that she will choose the same brand
202 Chapter 3 Random Variables and Distributions
chosen on her previous purchase, and the probability is
2/3 that she will switch brands.
a. If her first purchase is brandA, what is the probability
that her fifth purchase will be brand B?
b. If her first purchase is brandB, what is the probability
that her fifth purchase will be brand B?
12. Suppose that three boys A, B, and C are throwing a
ball from one to another. Whenever A has the ball, he
throws it to B with a probability of 0.2 and to C with a
probability of 0.8. Whenever B has the ball, he throws it
to A with a probability of 0.6 and to C with a probability of
0.4.Whenever C has the ball, he is equally likely to throw
it to either A or B.
a. Consider this process to be a Markov chain and construct
the transition matrix.
b. If each of the three boys is equally likely to have the
ball at a certain time n, which boy is most likely to
have the ball at time n + 2?
13. Suppose that a coin is tossed repeatedly in such a way
that heads and tails are equally likely to appear on any
given toss and that all tosses are independent, with the
following exception:Whenever either three heads or three
tails have been obtained on three successive tosses, then
the outcome of the next toss is always of the opposite type.
At time n (n ≥ 3), let the state of this process be specified
by the outcomes on tosses n − 2, n − 1, and n. Show that
this process is a Markov chain with stationary transition
probabilities and construct the transition matrix.
14. There are two boxes A and B, each containing red and
green balls. Suppose that box A contains one red ball and
two green balls and box B contains eight red balls and two
green balls. Consider the following process: One ball is
selected at random from box A, and one ball is selected
at random from box B. The ball selected from box A is
then placed in box B and the ball selected from box B is
placed in boxA.These operations are then repeated indefinitely.
Show that the numbers of red balls in box A form a
Markov chain with stationary transition probabilities, and
construct the transition matrix of the Markov chain.
15. Verify the rows of the transition matrix in Example
3.10.6 that correspond to current states {AA, Aa} and
{Aa, aa}.
16. Let the initial probability vector in Example 3.10.6 be
v = (1/16, 1/4, 1/8, 1/4, 1/4, 1/16). Find the probabilities
of the six states after one generation.
17. Return to Example 3.10.6. Assume that the state at
time n − 1 is {Aa, aa}.
a. Suppose that we learn thatXn+1 is {AA, aa}. Find the
conditional distribution of Xn. (That is, find all the
probabilities for the possible states at time n given
that the state at time n + 1 is {AA, aa}.)
b. Suppose that we learn that Xn+1 is {aa, aa}. Find the
conditional distribution of Xn.
18. Return to Example 3.10.13. Prove that the stationary
distributions described there are the only stationary distributions
for that Markov chain.
19. Find the unique stationary distribution for the Markov
chain in Exercise 2.

::: {#exr-3-10-20}

# Exercise 3.10.20

The unique stationary distribution in Exercise 9 is v =
(0, 1, 0, 0). This is an instance of the following general result:
Suppose that a Markov chain has exactly one absorbing
state. Suppose further that, for each non-absorbing
state k, there is n such that the probability is positive of
moving from state k to the absorbing state in n steps. Then
the unique stationary distribution has probability 1 in the
absorbing state. Prove this result.

:::
