
## Continuous Distributions {#sec-3-2}

*Next, we focus on random variables that can assume every value in an interval (bounded or unbounded). If a random variable $X$ has associated with it a function $f$ such that the integral of $f$ over each interval gives the probability that X is in the interval, then we call $f$ the probability density function (PDF) of $X$ and we say that $X$ has a continuous distribution.*

### The Probability Density Function

::: {.callout-tip}

::: {#exm-3-2-1}

# Example 3.2.1: Demands for Utilities

In Example 3.1.5, we determined the distribution of the demand
for water, X. From Fig. 3.2, we see that the smallest possible value of X is 4
and the largest is 200. For each interval C = [c0, c1]⊂ [4, 200], Eq. (3.1.2) says that
Pr(c0 ≤ X ≤ c1) = 149(c1 − c0)
29204
= c1 − c0
196
=
  c1
c0
1
196
dx.
3.2 Continuous Distributions 101
So, if we define
f (x) =
⎧⎨
⎩
1
196
if 4 ≤ x ≤ 200,
0 otherwise,
(3.2.1)
we have that
Pr(c0 ≤ X ≤ c1) =
  c1
c0
f (x)dx. (3.2.2)
Because we defined f (x) to be 0 for x outside of the interval [4, 200], we see that Eq.
(3.2.2) holds for all c0 ≤ c1, even if c0 =−∞and/or c1=∞.

:::

:::
 
The water demand $X$ in @exm-3-2-1 is an example of the following.

::: {.callout-tip}

::: {#def-3-2-1}

# Definition 3.2.1: Continuous Distribution/Random Variable

We say that a random variable X has a
continuous distribution or that X is a continuous random variable if there exists a
nonnegative function f , defined on the real line, such that for every interval of real
numbers (bounded or unbounded), the probability thatX takes a value in the interval
is the integral of f over the interval.

:::

:::

For example, in the situation described in Definition 3.2.1, for each bounded closed
interval [a, b],
Pr(a ≤ X ≤ b) =
  b
a
f (x) dx. (3.2.3)
Similarly, Pr(X ≥ a) =
  ∞
a f (x) dx and Pr(X ≤ b) =
  b
−∞ f (x) dx.
We see that the function f characterizes the distribution of a continuous random
variable in much the same way that the probability function characterizes the
distribution of a discrete random variable. For this reason, the function f plays an
important role, and hence we give it a name.

::: {.callout-tip}

::: {#def-3-2-2}

# Definition 3.2.2: Probability Density Function/PDF/Support

If $X$ has a continuous distribution, the function f described in @def-3-2-1 is called the **probability density function**
(abbreviated PDF) of $X$. The closure of the set $\{x : f(x) > 0\}$ is called the **support** of (the distribution of) $X$.

:::

:::

@exm-3-2-1 demonstrates that the water demand $X$ has PDF given by (3.2.1).

Every PDF $f$ must satisfy the following two requirements:

$$
f (x) ≥ 0, for all x, (3.2.4)
$$

and

$$
  ∞
−∞
f (x) dx = 1. (3.2.5)
$$

A typical PDF is sketched in Fig. 3.4. In that figure, the total area under the curve
must be 1, and the value of Pr(a ≤ X ≤ b) is equal to the area of the shaded region.

**Note: Continuous Distributions Assign Probability 0 to Individual Values**. The integral in Eq. (3.2.3) also equals Pr(a < X ≤ b) as well as $\Pr(a < X < b)$ and $\Pr(a \leq X < b)$. Hence, it follows from the definition of continuous distributions that, if X
has a continuous distribution, Pr(X = a) = 0 for each number a. As we noted on
page 20, the fact that Pr(X = a) = 0 does not imply that X = a is impossible. If it did, 

all values of X would be impossible and X couldn’t assume any value.What happens
is that the probability in the distribution of X is spread so thinly that we can only see
it on sets like nondegenerate intervals. It is much the same as the fact that lines have
0 area in two dimensions, but that does not mean that lines are not there. The two
vertical lines indicated under the curve in Fig. 3.4 have 0 area, and this signifies that
Pr(X = a) = Pr(X = b) = 0. However, for each   > 0 and each a such that f (a)>0,
Pr(a −   ≤ X ≤ a +  ) ≈ 2 f (a) > 0.

::: {#fig-3-4}

a b x
f (x)

An example of a PDF
:::

### Nonuniqueness of the PDF

If a random variable X has a continuous distribution, then Pr(X = x) = 0 for every
individual value x. Because of this property, the values of each p.d.f. can be changed
at a finite number of points, or even at certain infinite sequences of points, without
changing the value of the integral of the p.d.f. over any subset A. In other words,
the values of the p.d.f. of a random variable X can be changed arbitrarily at many
points without affecting any probabilities involving X, that is, without affecting the
probability distribution of X. At exactly which sets of points we can change a p.d.f.
depends on subtle features of the definition of the Riemann integral. We shall not
deal with this issue in this text, and we shall only contemplate changes to p.d.f.’s at
finitely many points.
To the extent just described, the p.d.f. of a random variable is not unique. In many
problems, however, there will be one version of the p.d.f. that is more natural than
any other because for this version the p.d.f. will, wherever possible, be continuous on
the real line. For example, the p.d.f. sketched in Fig. 3.4 is a continuous function over
the entire real line. This p.d.f. could be changed arbitrarily at a few points without
affecting the probability distribution that it represents, but these changes would
introduce discontinuities into the p.d.f. without introducing any apparent advantages.
Throughout most of this book, we shall adopt the following practice: If a random
variable X has a continuous distribution, we shall give only one version of the p.d.f.
of X and we shall refer to that version as the p.d.f. of X, just as though it had been
uniquely determined. It should be remembered, however, that there is some freedom
in the selection of the particular version of the p.d.f. that is used to represent each
continuous distribution. The most common place where such freedom will arise is
in cases like Eq. (3.2.1) where the p.d.f. is required to have discontinuities. Without
making the function f any less continuous, we could have defined the p.d.f. in that
example so that f (4) = f (200) = 0 instead of f (4) = f (200) = 1/196. Both of these
choices lead to the same calculations of all probabilities associated with X, and they are both equally valid. Because the support of a continuous distribution is the closure
of the set where the p.d.f. is strictly positive, it can be shown that the support is unique.
Asensible approach would then be to choose the version of the p.d.f. that was strictly
positive on the support whenever possible.
The reader should note that “continuous distribution” is not the name of a
distribution, just as “discrete distribution” is not the name of a distribution. There are
many distributions that are discrete and many that are continuous. Some distributions
of each type have names that we either have introduced or will introduce later.
We shall now present several examples of continuous distributions and their PDFs.

### Uniform Distributions on Intervals

::: {.callout-tip}

::: {#exm-3-2-2}

# Example 3.2.2: Temperature Forecasts

Television weather forecasters announce high and low temperature forecasts as integer numbers of degrees. These forecasts, however, are the results of very sophisticated weather models that provide more precise forecasts that the television personalities round to the nearest integer for simplicity. Suppose that the forecaster announces a high temperature of y. If we wanted to know what temperature $X$ the weather models actually produced, it might be safe to assume that $X$ was equally likely to be any number in the interval from $y − 1/2$ to $y + 1/2$.  

:::

:::

The distribution of $X$ in @exm-3-2-2 is a special case of the following.

::: {.callout-tip}

::: {#def-3-2-3}

# Definition 3.2.3: Uniform Distribution on an Interval

Let $a$ and $b$ be two given real numbers such that $a < b$. Let $X$ be a random variable such that it is known that $a \leq X \leq b$ and, for every subinterval of $[a, b]$, the probability that $X$ will belong to that subinterval is proportional to the length of that subinterval. We then say that the random variable $X$ has the **uniform distribution** on the interval $[a, b]$.

:::

:::

A random variable $X$ with the uniform distribution on the interval $[a, b]$ represents the outcome of an experiment that is often described by saying that a point is chosen at random from the interval $[a, b]$. In this context, the phrase "at random" means that the point is just as likely to be chosen from any particular part of the interval as from any other part of the same length.

::: {.callout-tip}

::: {#thm-3-2-1}

# Theorem 3.2.1: Uniform Distribution PDF

If $X$ has the uniform distribution on an interval $[a, b]$, then
the PDF of $X$ is
f (x) =
 
1
b − a
for a ≤ x ≤ b,
0 otherwise.
(3.2.6)
Proof X must take a value in the interval [a, b]. Hence, the p.d.f. f (x) of X must
be 0 outside of [a, b]. Furthermore, since any particular subinterval of [a, b] having
a given length is as likely to contain X as is any other subinterval having the same
length, regardless of the location of the particular subinterval in [a, b], it follows that
f (x) must be constant throughout [a, b], and that interval is then the support of the
distribution. Also,
  ∞
−∞
f (x) dx =
  b
a
f (x) dx = 1. (3.2.7)
Therefore, the constant value of f (x) throughout [a, b] must be 1/(b − a), and the
p.d.f. of X must be (3.2.6).

:::

:::

Figure 3.5 The p.d.f. for the
uniform distribution on the
interval [a, b].
a b x
f (x)
Th p.d.f. (3.2.6) is sketched in Fig. 3.5. As an example, the random variableX(demand
for water) in Example 3.2.1 has the uniform distribution on the interval [4, 200].
Note: Density Is Not Probability. The reader should note that the p.d.f. in (3.2.6) can
be greater than 1, particularly if b −a <1. Indeed, p.d.f.’s can be unbounded, as we
shall see in @exm-3-2-6. The PDF of X, f (x), itself does not equal the probability
that X is near x. The integral of f over values near x gives the probability that X is
near x, and the integral is never greater than 1.
It is seen from Eq. (3.2.6) that the p.d.f. representing a uniform distribution on
a given interval is constant over that interval, and the constant value of the p.d.f.
is the reciprocal of the length of the interval. It is not possible to define a uniform
distribution over an unbounded interval, because the length of such an interval is
infinite.
Consider again the uniform distribution on the interval [a, b]. Since the probability
is 0 that one of the endpoints a or b will be chosen, it is irrelevant whether the
distribution is regarded as a uniform distribution on the closed interval a ≤ x ≤ b, or
as a uniform distribution on the open intervala <x <b, or as a uniform distribution
on the half-open and half-closed interval (a, b] in which one endpoint is included and
the other endpoint is excluded.
For example, if a random variable X has the uniform distribution on the interval
[−1, 4], then the p.d.f. of X is
f (x) =
 
1/5 for −1≤ x ≤ 4,
0 otherwise.
Furthermore,
Pr(0 ≤X<2) =
  2
0
f (x) dx = 2
5
.
Notice that we defined the p.d.f. of X to be strictly positive on the closed interval
[−1, 4] and 0 outside of this closed interval. It would have been just as sensible to
define the p.d.f. to be strictly positive on the open interval (−1, 4) and 0 outside of this
open interval. The probability distribution would be the same either way, including
the calculation of Pr(0 ≤X <2) that we just performed. After this, when there are
several equally sensible choices for how to define a p.d.f., we will simply choose one
of them without making any note of the other choices.
Other Continuous Distributions
Example
3.2.3
Incompletely Specified p.d.f. Suppose that the p.d.f. of a certain random variable X
has the following form:
3.2 Continuous Distributions 105
f (x) =
 
cx for 0 < x <4,
0 otherwise,
where c is a given constant. We shall determine the value of c.
For every p.d.f., it must be true that
  ∞
−∞ f (x) = 1. Therefore, in this example,
  4
0
cx dx = 8c = 1.
Hence, c = 1/8.  
Note: Calculating Normalizing Constants. The calculation in Example 3.2.3 illustrates
an important point that simplifies many statistical results. The p.d.f. of X was
specified without explicitly giving the value of the constant c. However, we were able
to figure out what was the value of c by using the fact that the integral of a p.d.f. must
be 1. It will often happen, especially in Chapter 8 where we find sampling distributions
of summaries of observed data, that we can determine the p.d.f. of a random
variable except for a constant factor. That constant factor must be the unique value
such that the integral of the p.d.f. is 1, even if we cannot calculate it directly.

::: {.callout-tip}

::: {#exm-3-2-4}

# Example 3.2.4: Calculating Probabilities from a PDF (DeGroot and Schervish, p. 105)

Suppose that the PDF of $X$ is as in @exm-3-2-3, namely,

$$
f(x) = \begin{cases}
\frac{x}{8} &\text{for }0 < x < 4, \\
0 &\text{otherwise.}
\end{cases}
$$

We shall now determine the values of $\Pr(1 \leq X \leq 2)$ and $\Pr(X > 2)$. Apply Eq. (3.2.3) to get

$$
\Pr(1 \leq X \leq 2) = \int_1^2 \frac{1}{8}xdx = \frac{3}{16}
$$

and

$$
\Pr(X > 2) = \int_2^4 \frac{1}{8}xdx = \frac{3}{4}.
$$

:::

:::

::: {.callout-tip}

::: {#exm-3-2-5}

# Example 3.2.5: Unbounded Random Variables

It is often convenient and useful to represent a continuous
distribution by a p.d.f. that is positive over an unbounded interval of the real
line. For example, in a practical problem, the voltage X in a certain electrical system
might be a random variable with a continuous distribution that can be approximately
represented by the p.d.f.
f (x) =
⎧⎨
⎩
0 for x ≤ 0,
1
(1+ x)2 for x >0.
(3.2.8)
It can be verified that the properties (3.2.4) and (3.2.5) required of all p.d.f.’s are
satisfied by f (x).
Even though the voltage X may actually be bounded in the real situation, the
p.d.f. (3.2.8) may provide a good approximation for the distribution of X over its full
range of values. For example, suppose that it is known that the maximum possible
value of X is 1000, in which case Pr(X > 1000) = 0. When the p.d.f. (3.2.8) is used,
we compute Pr(X > 1000) = 0.001. If (3.2.8) adequately represents the variability
of X over the interval (0, 1000), then it may be more convenient to use the p.d.f.
(3.2.8) than a p.d.f. that is similar to (3.2.8) for x ≤ 1000, except for a new normalizing constant, and is 0 forx >1000. This can be especially true if we do not know for sure
that the maximum voltage is only 1000.

:::

:::

::: {.callout-tip}

::: {#exm-3-2-6}

# Example 3.2.6: Unbounded PDFs

Since a value of a PDF is a probability density, rather than a
probability, such a value can be larger than $1$. In fact, the values of the following PDF are unbounded in the neighborhood of $x = 0$:

$$
f(x) = \begin{cases}
\frac{2}{3}x^{-1/3} &\text{for }0 < x < 1, \\
0 &\text{otherwise.}
\end{cases}
$$ {#eq-3-2-9}

It can be verified that even though the PDF @eq-3-2-9 is unbounded, it satisfies the properties (3.2.4) and (3.2.5) required of a PDF.

:::

:::

### Mixed Distributions

Most distributions that are encountered in practical problems are either discrete or continuous. We shall show, however, that it may sometimes be necessary to consider a distribution that is a mixture of a discrete distribution and a continuous distribution.

::: {.callout-tip}

::: {#exm-3-2-7}

# Example 3.2.7: Truncated Voltage (DeGroot and Schervish, p. 106)

Suppose that in the electrical system considered in @exm-3-2-5, the voltage $X$ is to be measured by a voltmeter that will record the actual value of $X$ if $X \leq 3$ but will simply record the value $3$ if $X > 3$. If we let $Y$ denote the value recorded by the voltmeter, then the distribution of $Y$ can be derived as follows.

First, $Pr(Y = 3) = Pr(X \geq 3) = 1/4$. Since the single value $Y = 3$ has probability $1/4$, it follows that $\Pr(0 < Y < 3) = 3/4$. Furthermore, since $Y = X$ for $0 < X < 3$, this probability $3/4$ for $Y$ is distributed over the interval $(0, 3)$ according to the same PDF (3.2.8) as that of $X$ over the same interval. Thus, the distribution of $Y$ is specified by the combination of a PDF over the interval $(0, 3)$ and a positive probability at the point $Y = 3$.

:::

:::

### Summary

A continuous distribution is characterized by its probability density function (PDF). A nonnegative function $f$ is the PDF of the distribution of $X$ if, for every interval $[a, b]$, $\Pr(a \leq X \leq b) = \int_a^b f(x)dx$. Continuous random variables satisfy $\Pr(X = x) = 0$ for every value $x$. If the PDF of a distribution is constant on an interval $[a, b]$ and is 0 off the interval, we say that the distribution is uniform on the interval $[a, b]$.

### Exercises

::: {#exr-3-2-1}

# Exercise 3.2.1

Let X be a random variable with the PDF specified in
@exm-3-2-6. Compute $\Pr(X \leq 8/27)$.

:::

::: {#exr-3-2-2}

# Exercise 3.2.2

Suppose that the PDF of a random variable $X$ is as
follows:

$$
f(x) = \begin{cases}
\frac{4}{3}(1-x^3) &\text{for }0 < x < 1, \\
0 &\text{otherwise.}
\end{cases}
$$

Sketch this PDF and determine the values of the following
probabilities:

(a) $\Pr\left(X < \frac{1}{2}\right)$

(b) $\Pr\left(\frac{1}{4} < X < \frac{3}{4}\right)$

(c) $\Pr\left(X > \frac{1}{3}\right)$

:::

::: {#exr-3-2-3}

# Exercise 3.2.3

Suppose that the PDF of a random variable $X$ is as
follows:

$$
f(x) = \begin{cases}
\frac{1}{36}(9 - x^2) &\text{for }-3 \leq x \leq 3, \\
0 &\text{otherwise.}
\end{cases}
$$

Sketch this p.d.f. and determine the values of the following
probabilities:

(a) $\Pr(X < 0)$

(b) $\Pr(−1 \leq X \leq 1)$

(c) $\Pr(X > 2)$.

:::

::: {#exr-3-2-4}

# Exercise 3.2.4

4. Suppose that the p.d.f. of a random variable X is as
follows:
f (x) =
 
cx2 for 1≤ x ≤ 2,
0 otherwise.
a. Find the value of the constant c and sketch the p.d.f.
b. Find the value of Pr(X > 3/2).

:::

::: {#exr-3-2-5}

# Exercise 3.2.5

Suppose that the p.d.f. of a random variable X is as
follows:
f (x) =
 
1
8x for 0 ≤ x ≤ 4,
0 otherwise.
a. Find the value of t such that Pr(X ≤ t) = 1/4.
b. Find the value of t such that Pr(X ≥ t) = 1/2.

:::

::: {#exr-3-2-6}

# Exercise 3.2.6

Let X be a random variable for which the p.d.f. is as
given in Exercise 5. After the value of X has been observed,
let Y be the integer closest to X. Find the p.f. of
the random variable Y .

:::

::: {#exr-3-2-7}

# Exercise 3.2.7

Suppose that a random variable X has the uniform
distribution on the interval [−2, 8]. Find the p.d.f. ofX and
the value of Pr(0<X <7).

:::

::: {#exr-3-2-8}

# Exercise 3.2.8

Suppose that the p.d.f. of a random variable X is as
follows:

$$
f(x) = \begin{cases}
ce^{-2x} &\text{for }x > 0, \\
0 &\text{otherwise.}
\end{cases}
$$

(a) Find the value of the constant $c$ and sketch the PDF.

(b) Find the value of $\Pr(1 < X < 2)$.

:::

::: {#exr-3-2-9}

# Exercise 3.2.9

Show that there does not exist any number c such that
the following function f (x) would be a p.d.f.:
f (x) =
  c
1+x for x >0,
0 otherwise.

:::

::: {#exr-3-2-10}

# Exercise 3.2.10

Suppose that the p.d.f. of a random variable X is as
follows:
f (x) =
  c
(1−x)1/2 for 0 < x <1,
0 otherwise.
a. Find the value of the constant c and sketch the p.d.f.
b. Find the value of Pr(X ≤ 1/2).

:::

::: {#exr-3-2-11}

# Exercise 3.2.11

Show that there does not exist any number c such that
the following function f (x) would be a p.d.f.:
f (x) =
  c
x for 0 < x <1,
0 otherwise.

:::

::: {#exr-3-2-12}

# Exercise 3.2.12

In Example 3.1.3 on page 94, determine the distribution
of the random variable Y , the electricity demand.
Also, find Pr(Y < 50).

:::

::: {#exr-3-2-13}

# Exercise 3.2.13

An ice cream seller takes 20 gallons of ice cream in
her truck each day. Let X stand for the number of gallons
that she sells. The probability is 0.1 that X = 20. If she
doesn’t sell all 20 gallons, the distribution of X follows a
continuous distribution with a p.d.f. of the form
f (x) =
 
cx for 0 < x <20,
0 otherwise,
where c is a constant that makes Pr(X < 20) = 0.9. Find the
constant c so that Pr(X < 20) = 0.9 as described above.

:::
