
## The Cumulative Distribution Function {#sec-3-3}

*Although a discrete distribution is characterized by its PMF and a continuous distribution is characterized by its PDF, every distribution has a common characterization through its (cumulative) distribution function (CDF). The inverse of the CDF is called the quantile function, and it is useful for indicating where the probability is located in a distribution.*

::: {.callout-tip}

::: {#exm-3-3-1}

# Example 3.3.1: Voltage (DeGroot and Schervish, pp. 107-108)

Consider again the voltage X from Example 3.2.5. The distribution of X
is characterized by the p.d.f. in Eq. (3.2.8). An alternative characterization that is
more directly related to probabilities associated withXis obtained from the following
function:
108 Chapter 3 Random Variables and Distributions
F(x) = Pr(X ≤ x) =
  x
−∞
f (y)dy =
⎧⎨
⎩
 0 for x ≤ 0, x
0
dy
(1+ y)2 for x >0, = 0 for x ≤ 0,
1− 1
1+ x
for x >0.
(3.3.1)
So, for example, Pr(X ≤ 3) = F(3) = 3/4.  

:::

:::

### Definition and Basic Properties

::: {.callout-tip}

::: {#def-3-3-1}

# Definition 3.3.1: Cumulative Distribution Function (DeGroot and Schervish, p. 108)

The distribution function or cumulative distribution
function (abbreviated c.d.f.) F of a random variable X is the function
F(x) = Pr(X ≤ x) for −∞< x <∞. (3.3.2)

:::

:::

It should be emphasized that the cumulative distribution function is defined as above
for every random variable X, regardless of whether the distribution of X is discrete,
continuous, or mixed. For the continuous random variable in Example 3.3.1, the c.d.f.
was calculated in Eq. (3.3.1). Here is a discrete example:

::: {.callout-tip}

::: {#exm-3-3-2}

# Example 3.3.2: Bernoulli CDF

Let $X$ have the Bernoulli distribution with parameter p defined in
Definition 3.1.5. Then Pr(X = 0) = 1− p and Pr(X = 1) = p. Let F be the c.d.f. of X.
It is easy to see that F(x) = 0 forx <0 because X ≥ 0 for sure. Similarly, F(x) = 1 for
x ≥ 1 because X ≤ 1 for sure. For 0 ≤x <1, Pr(X ≤ x) = Pr(X = 0) = 1− p because
0 is the only possible value of X that is in the interval (−∞, x]. In summary,
F(x) =
⎧⎨
⎩
0 for x <0,
1− p for 0 ≤x <1,
1 for x ≥ 1.  

:::

:::

We shall soon see (Theorem 3.3.2) that the c.d.f. allows calculation of all interval
probabilities; hence, it characterizes the distribution of a random variable. It follows
from Eq. (3.3.2) that the c.d.f. of each random variable X is a function F defined on
the real line. The value of F at every point x must be a number F(x) in the interval
[0, 1] because F(x) is the probability of the event {X ≤ x}. Furthermore, it follows
from Eq. (3.3.2) that the c.d.f. of every random variable X must have the following
three properties.

::: {.callout-tip}

Property
3.3.1
Nondecreasing. The function F(x) is nondecreasing as x increases; that is, if x1< x2,
then F(x1) ≤ F(x2).
Proof If x1 < x2, then the event {X ≤ x1} is a subset of the event {X ≤ x2}. Hence,
Pr{X ≤ x1} ≤ Pr{X ≤ x2} according to Theorem 1.5.4.

:::


An example of a c.d.f. is sketched in Fig. 3.6. It is shown in that figure that 0 ≤
F(x) ≤ 1 over the entire real line. Also, F(x) is always nondecreasing as x increases,
although F(x) is constant over the interval x1 ≤ x ≤ x2 and for x ≥ x4.

::: {.callout-tip}

Property
3.3.2
Limits at ±∞. limx→−∞ F(x) = 0 and limx→∞ F(x) = 1.
Proof As in the proof of Property 3.3.1, note that {X ≤ x1} ⊂ {X ≤ x2} whenever x1<
x2. The fact that Pr(X ≤ x) approaches 0 as x→−∞now follows from Exercise 13 in Section 1.10. Similarly, the fact that Pr(X ≤ x) approaches 1 as x→∞follows from
Exercise 12 in Sec. 1.10.

::: {#fig-3-6}

1
z3
z2
z1
z0
0 x1 x2 x3 x4
x
F(x)

An example of a CDF
:::

The limiting values specified in Property 3.3.2 are indicated in Fig. 3.6. In this
figure, the value of F(x) actually becomes 1 at x = x4 and then remains 1 for x >x4.
Hence, it may be concluded that Pr(X ≤ x4) = 1 and Pr(X > x4) = 0. On the other
hand, according to the sketch in Fig. 3.6, the value of F(x) approaches 0 as x→−∞,
but does not actually become 0 at any finite point x. Therefore, for every finite value
of x, no matter how small, Pr(X ≤ x) > 0.
A c.d.f. need not be continuous. In fact, the value of F(x) may jump at any
finite or countable number of points. In Fig. 3.6, for instance, such jumps or points
of discontinuity occur where x = x1 and x = x3. For each fixed value x, we shall let
F(x
−
) denote the limit of the values of F(y) as y approaches x from the left, that is,
as y approaches x through values smaller than x. In symbols,

$$
F(x^{-}) = \lim_{y \rightarrow x, y < x}F(y).
$$

Similarly, we shall define $F(x^+)$ as the limit of the values of $F(y)$ as $y$ approaches $x$
from the right. Thus,

$$
F(x^+) = \lim_{y \rightarrow x, y > x}F(y).
$$

If the CDF is continuous at a given point $x$, then $F(x^{-}) = F(x^+) = F(x)$ at that point.

::: {.callout-tip}

Property
3.3.3
Continuity from the Right. A c.d.f. is always continuous from the right; that is, F(x) =
F(x
+
) at every point x.
Proof Let y1 > y2 > . . . be a sequence of numbers that are decreasing such that
limn→∞ yn
= x. Then the event {X ≤ x} is the intersection of all the events {X ≤ yn
}
for n = 1, 2, . . . . Hence, by Exercise 13 of Sec. 1.10,
F(x) = Pr(X ≤ x) = lim
n→∞ Pr(X ≤ yn) = F(x
+
).

:::

It follows from Property 3.3.3 that at every point x at which a jump occurs,
F(x
+
) = F(x) and F(x
−
) < F(x).

In Fig. 3.6 this property is illustrated by the fact that, at the points of discontinuity
x = x1 and x = x3, the value of F(x1) is taken as z1 and the value of F(x3) is taken as
z3.

### Determining Probabilities from the Distribution Function

::: {.callout-tip}

::: {#exm-3-3-3}

Example
3.3.3
Voltage. In Example 3.3.1, suppose that we want to know the probability that X lies
in the interval [2, 4]. That is, we want Pr(2 ≤ X ≤ 4). The c.d.f. allows us to compute
Pr(X ≤ 4) and Pr(X ≤ 2). These are related to the probability that we want as follows:
Let A = {2<X ≤ 4}, B = {X ≤ 2}, and C = {X ≤ 4}. Because X has a continuous
distribution, Pr(A) is the same as the probability that we desire.We see that A ∪ B =
C, and it is clear that A and B are disjoint. Hence, Pr(A) + Pr(B) = Pr(C). It follows
that
Pr(A) = Pr(C) − Pr(B) = F(4) − F(2) = 4
5
− 3
4
= 1
20

:::

:::

The type of reasoning used in Example 3.3.3 can be extended to find the probability
that an arbitrary random variable X will lie in any specified interval of the
real line from the c.d.f. We shall derive this probability for four different types of
intervals.
Theorem
3.3.1
For every value x,
Pr(X > x) = 1− F(x). (3.3.3)
Proof The events {X >x} and {X ≤ x} are disjoint, and their union is the whole
sample space S whose probability is 1. Hence, Pr(X > x) + Pr(X ≤ x) = 1. Now,
Eq. (3.3.3) follows from Eq. (3.3.2).
Theorem
3.3.2
For all values x1 and x2 such that x1< x2,
Pr(x1<X ≤ x2) = F(x2) − F(x1). (3.3.4)
Proof Let A = {x1<X ≤ x2}, B = {X ≤ x1}, and C = {X ≤ x2}. As in Example 3.3.3,
A and B are disjoint, and their union is C, so
Pr(x1<X ≤ x2) + Pr(X ≤ x1) = Pr(X ≤ x2).
Subtracting Pr(X ≤ x1) from both sides of this equation and applying Eq. (3.3.2)
yields Eq. (3.3.4).
For example, if the c.d.f. of X is as sketched in Fig. 3.6, then it follows from
Theorems 3.3.1 and 3.3.2 that Pr(X > x2) = 1− z1 and Pr(x2<X≤ x3) = z3 − z1. Also,
since F(x) is constant over the interval x1 ≤ x ≤ x2, then Pr(x1<X ≤ x2) = 0.
It is important to distinguish carefully between the strict inequalities and the
weak inequalities that appear in all of the preceding relations and also in the next
theorem. If there is a jump in F(x) at a given value x, then the values of Pr(X ≤ x)
and Pr(X < x) will be different.

::: {.callout-tip}

::: {#thm-3-3-3}

# Theorem 3.3.3

For each value x,
Pr(X < x) = F(x
−
). (3.3.5)
3.3 The Cumulative Distribution Function 111
Proof Let y1<y2 < . . . be an increasing sequence of numbers such that limn→∞ yn
=
x. Then it can be shown that
{X<x} =
∞ 
n=1
{X ≤ yn
}.
Therefore, it follows from Exercise 12 of Sec. 1.10 that
Pr(X < x) = lim
n→∞ Pr(X ≤ yn)
= lim
n→∞
F(yn) = F(x
−
).

:::

:::

For example, for the c.d.f. sketched in Fig. 3.6, Pr(X < x3) = z2 and Pr(X < x4)
= 1.
Finally, we shall show that for every value x, Pr(X = x) is equal to the amount
of the jump that occurs in F at the point x. If F is continuous at the point x, that is,
if there is no jump in F at x, then Pr(X = x) = 0.

::: {.callout-tip}

::: {#thm-3-3-4}

Theorem
3.3.4
For every value x,
Pr(X = x) = F(x) − F(x
−
). (3.3.6)
Proof It is always true that Pr(X = x) = Pr(X ≤ x) − Pr(X < x). The relation (3.3.6)
follows from the fact that Pr(X ≤ x) = F(x) at every point and from Theorem 3.3.3.

:::

:::

In Fig. 3.6, for example, Pr(X = x1) = z1 − z0, Pr(X = x3) = z3 − z2, and the
probability of every other individual value of X is 0.

### The CDF of a Discrete Distribution

From the definition and properties of a c.d.f. F(x), it follows that if a < b and
if Pr(a <X < b) = 0, then F(x) will be constant and horizontal over the interval
a <x <b. Furthermore, aswe have just seen, at every point x such that Pr(X = x)>0,
the c.d.f. will jump by the amount Pr(X = x).
Suppose that X has a discrete distribution with the p.f. f (x). Together, the properties
of a c.d.f. imply that F(x) must have the following form: F(x) will have a jump
of magnitude f (xi) at each possible value xi of X, and F(x) will be constant between
every pair of successive jumps. The distribution of a discrete random variable X can
be represented equally well by either the p.f. or the c.d.f. of X.

### The CDF of a Continuous Distribution

::: {.callout-tip}

::: {#thm-3-3-5}

# Theorem 3.3.5

Let X have a continuous distribution, and let f (x) and F(x) denote its p.d.f. and the
c.d.f., respectively. Then F is continuous at every x,
F(x) =
  x
−∞
f (t) dt, (3.3.7)
and
dF(x)
dx
= f (x), (3.3.8)
at all x such that f is continuous.

Proof Since the probability of each individual point x is 0, the c.d.f. F(x) will have
no jumps. Hence, F(x) will be a continuous function over the entire real line.
By definition, F(x) = Pr(X ≤ x). Since f is the p.d.f. of X, we have from the
definition of p.d.f. that Pr(X ≤ x) is the right-hand side of Eq. (3.3.7).
It follows from Eq. (3.3.7) and the relation between integrals and derivatives
(the fundamental theorem of calculus) that, for every x at which f is continuous,
Eq. (3.3.8) holds.

:::

:::

Thus, the c.d.f. of a continuous random variable X can be obtained from the p.d.f.
and vice versa. Eq. (3.3.7) is how we found the c.d.f. in Example 3.3.1. Notice that
the derivative of the F in Example 3.3.1 is
F
 
(x) =
⎧⎨
⎩
0 for x <0,
1
(1+ x)2 for x >0,
and F
  does not exist at x = 0. This verifies Eq (3.3.8) for Example 3.3.1. Here, we
have used the popular shorthand notation F
 
(x) for the derivative of F at the point x.
Example
3.3.4
Calculating a p.d.f. from a c.d.f. Let the c.d.f. of a random variable be
F(x) =
⎧⎪⎨
⎪⎩
0 for x <0,
x2/3 for 0 ≤ x ≤ 1,
1 for x >1.
This function clearly satisfies the three properties required of every c.d.f., as given
earlier in this section. Furthermore, since this c.d.f. is continuous over the entire real
line and is differentiable at every point except x = 0 and x = 1, the distribution of X
is continuous. Therefore, the p.d.f. of X can be found at every point other than x = 0
and x = 1 by the relation (3.3.8). The value of f (x) at the points x = 0 and x = 1 can
be assigned arbitrarily.When the derivative F
 
(x) is calculated, it is found that f (x)
is as given by Eq. (3.2.9) in Example 3.2.6. Conversely, if the p.d.f. of X is given by
Eq. (3.2.9), then by using Eq. (3.3.7) it is found that F(x) is as given in this example.

### The Quantile Function

::: {.callout-tip}

::: {#exm-3-3-5}

# Example 3.3.5: Fair Bets

Suppose that X is the amount of rain that will fall tomorrow, and X has
c.d.f. F. Suppose that we want to place an even-money bet on X as follows: If X ≤ x0,
we win one dollar and ifX>x0 we lose one dollar. In order to make this bet fair, we
need Pr(X ≤ x0) = Pr(X > x0) = 1/2.We could search through all of the real numbers
x trying to find one such that F(x) = 1/2, and then we would let x0 equal the value we
found. If F is a one-to-one function, then F has an inverse F
−1 and x0 = F
−1(1/2).

:::

:::

The value $x_0$ that we seek in @exm-3-3-5 is called the **0.5 quantile** of $X$ or the
**50th percentile** of $X$ because 50% of the distribution of $X$ is at or below $x_0$.

::: {.callout-tip}

::: {#def-3-3-2}

# Definition 3.3.2: Quantiles/Percentiles

Let X be a random variable with c.d.f. F. For each p strictly
between 0 and 1, define F
−1(p) to be the smallest value x such that F(x) ≥ p. Then
F
−1(p) is called the p quantile of X or the 100p percentile of X. The function F
−1
defined here on the open interval (0, 1) is called the quantile function of X.

:::

:::

::: {.callout-tip}

::: {#exm-3-3-6}

# Example 3.3.6: Standardized Test Scores

Many universities in the United States rely on standardized
test scores as part of their admissions process. Thousands of people take these tests
each time that they are offered. Each examinee’s score is compared to the collection
of scores of all examinees to see where it fits in the overall ranking. For example, if
83% of all test scores are at or below your score, your test report will say that you
scored at the 83rd percentile.  

:::

:::

The notation $F^{-1}(p)$ in @def-3-3-2 deserves some justification. Suppose first that the CDF $F$ of $X$ is continuous and one-to-one over the whole set of possible values of $X$. Then the inverse $F^{-1}$ of $F$ exists, and for each $0 < p < 1$, there is one and only one $x$ such that $F(x) = p$. That $x$ is $F^{−1}(p)$. @def-3-3-2 extends the concept of inverse function to nondecreasing functions (such as CDFs) that may be neither one-to-one nor continuous.

**Quantiles of Continuous Distributions**: When the CDF of a random variable $X$ is continuous and one-to-one over the whole set of possible values of $X$, the inverse $F^{-1}$ of $F$ exists and equals the quantile function of $X$.

::: {.callout-tip}

::: {#exm-3-3-7}

# Example 3.3.7: Value at Risk

The manager of an investment portfolio is interested in how much
money the portfolio might lose over a fixed time horizon. Let X be the change
in value of the given portfolio over a period of one month. Suppose that X has
the p.d.f. in Fig. 3.7. The manager computes a quantity known in the world of risk
management as Value at Risk (denoted by VaR). To be specific, let Y =−X stand
for the loss incurred by the portfolio over the one month. The manager wants to
have a level of confidence about how large Y might be. In this example, the manager
specifies a probability level, such as 0.99 and then finds y0, the 0.99 quantile of Y. The
manager is now 99% sure that Y ≤ y0, and y0 is called the VaR. If X has a continuous
distribution, then it is easy to see that y0 is closely related to the 0.01 quantile of
the distribution of X. The 0.01 quantile x0 has the property that Pr(X < x0) = 0.01.
But Pr(X < x0) = Pr(Y > −x0) = 1− Pr(Y ≤−x0). Hence, −x0 is a 0.99 quantile of
Y . For the p.d.f. in Fig. 3.7, we see that x0 =−4.14, as the shaded region indicates.
Then y0 = 4.14 is VaR for one month at probability level 0.99.  

:::

:::

::: {#fig-3-7}

0.02
0
0.12
0.10
0.08
0.06
0.04
 4.14
Change in value
Density
10 20
0.99
0.01
 20  10 0


The p.d.f. of the change in value of a portfolio with lower 1% indicated.
:::

::: {#fig-3-8}

0.2
1.0
0.8
0.6
p
0.4
0 1 2F 1( p)
Cumulative distribution function
3 4 x


The CDF of a uniform distribution indicating how to solve for a quantile.
:::

::: {.callout-tip}

::: {#exm-3-3-8}

# Example 3.3.8: Uniform Distribution on an Interval

Let X have the uniform distribution on the
interval [a, b]. The c.d.f. of X is
F(x) = Pr(X ≤ x) =
⎧⎪⎪⎨
⎪⎪⎩
 0 if x ≤ a, x
a
1
b − a
du if a <x ≤ b,
1 if x >b.
The integral above equals (x−a)/(b−a). So, F(x) = (x−a)/(b−a) for all a<x<b,
which is a strictly increasing function over the entire interval of possible values of X.
The inverse of this function is the quantile function of X, which we obtain by setting
F(x) equal to p and solving for x:
x − a
b − a
= p,
x − a = p(b − a),
x = a + p(b − a) = pb + (1− p)a.
Figure 3.8 illustrates how the calculation of a quantile relates to the c.d.f.
The quantile function ofX is F
−1(p) = pb + (1− p)a for $0 < p < 1$. In particular, $F^{-1}(1/2) = (b + a)/2$.  

:::

:::

**Note: Quantiles, Like CDFs, Depend on the Distribution Only**: Any two random variables with the same distribution have the same quantile function. When we refer to a quantile of $X$, we mean a quantile of the distribution of $X$.

**Quantiles of Discrete Distributions**: It is convenient to be able to calculate quantiles for discrete distributions as well. The quantile function of @def-3-3-2 exists for all distributions whether discrete, continuous, or otherwise. For example, in @fig-3-6, let
z0 ≤ p ≤ z1. Then the smallest x such that F(x) ≥ p is x1. For every value of x <x1,
we have F(x) < z0 ≤ p and F(x1) = z1. Notice that F(x) = z1 for all x between x1
and x2, but since x1 is the smallest of all those numbers, x1 is the p quantile. Because
distribution functions are continuous from the right, the smallest x such that F(x) ≥ p
exists for all 0<p <1. For p = 1, there is no guarantee that such an x will exist. For
example, in Fig. 3.6, F(x4) = 1, but in Example 3.3.1, F(x)<1 for all x. For p = 0,
there is never a smallest x such that F(x) = 0 because limx→−∞ F(x) = 0. That is, if
F(x0) = 0, then F(x) = 0 for all x <x0. For these reasons, we never talk about the 0
or 1 quantiles.
3.3 The Cumulative Distribution Function 115
Table 3.1 Quantile function
for Example 3.3.9
p F−1(p)
(0, 0.1681] 0
(0.1681, 0.5283] 1
(0.5283, 0.8370] 2
(0.8370, 0.9693] 3
(0.9693, 0.9977] 4
(0.9977, 1) 5
Example
3.3.9
Quantiles of a Binomial Distribution. Let X have the binomial distribution with parameters
5 and 0.3. The binomial table in the back of the book has the p.f. f of X,
which we reproduce here together with the c.d.f. F:
x 0 1 2 3 4 5
f (x) 0.1681 0.3602 0.3087 0.1323 0.0284 0.0024
F(x) 0.1681 0.5283 0.8370 0.9693 0.9977 1
(A little rounding error occurred in the p.f.) So, for example, the 0.5 quantile of this
distribution is 1, which is also the 0.25 quantile and the 0.20 quantile. The entire
quantile function is in Table 3.1. So, the 90th percentile is 3, which is also the 95th
percentile, etc.  
Certain quantiles have special names.
Definition
3.3.3
Median/Quartiles. The 1/2 quantile or the 50th percentile of a distribution is called its
median. The 1/4 quantile or 25th percentile is the lower quartile. The 3/4 quantile or
75th percentile is called the upper quartile.
Note: The Median Is Special. The median of a distribution is one of several special
features that people like to use when sumarizing the distribution of a random variable.
We shall discuss summaries of distributions in more detail in Chapter 4. Because
the median is such a popular summary, we need to note that there are several different
but similar “definitions” of median. Recall that the 1/2 quantile is the smallest
number x such that F(x) ≥ 1/2. For some distributions, usually discrete distributions,
there will be an interval of numbers [x1, x2) such that for all x ∈ [x1, x2), F(x) = 1/2.
In such cases, it is common to refer to all such x (including x2) as medians of the distribution.
(See Definition 4.5.1.) Another popular convention is to call (x1 + x2)/2
the median. This last is probably the most common convention. The readers should
be aware that, whenever they encounter a median, it might be any one of the things
that we just discussed. Fortunately, they all mean nearly the same thing, namely that
the number divides the distribution in half as closely as is possible.
116 Chapter 3 Random Variables and Distributions
Example
3.3.10
Uniform Distribution on Integers. Let X have the uniform distribution on the integers
1, 2, 3, 4. (See Definition 3.1.6.) The c.d.f. of X is
F(x) =
⎧⎪⎪⎪⎪⎪⎨
⎪⎪⎪⎪⎪⎩
0 ifx <1,
1/4 if1≤x <2,
1/2 if2≤x <3,
3/4 if3≤x <4,
1 ifx ≥ 4.
The 1/2 quantile is 2, but every number in the interval [2, 3] might be called a median.
The most popular choice would be 2.5.  
One advantage to describing a distribution by the quantile function rather than
by the c.d.f. is that quantile functions are easier to display in tabular form for multiple
distributions. The reason is that the domain of the quantile function is always the
interval (0, 1) no matter what the possible values of X are. Quantiles are also useful
for summarizing distributions in terms of where the probability is. For example, if
one wishes to say where the middle half of a distribution is, one can say that it lies
between the 0.25 quantile and the 0.75 quantile. In Sec. 8.5, we shall see how to use
quantiles to help provide estimates of unknown quantities after observing data.
In Exercise 19, you can show how to recover the c.d.f. from the quantile function.
Hence, the quantile function is an alternative way to characterize a distribution.
Summary
The c.d.f. F of a random variable X is F(x) = Pr(X ≤ x) for all real x. This function
is continuous from the right. If we let F(x
−
) equal the limit of F(y) as y approaches
x from below, then F(x) − F(x
−
) = Pr(X = x). A continuous distribution has a
continuous c.d.f. and F
 
(x) = f (x), the p.d.f. of the distribution, for all x at which
F is differentiable. A discrete distribution has a c.d.f. that is constant between the
possible values and jumps by f (x) at each possible value x. The quantile function
F
−1(p) is equal to the smallest x such that F(x) ≥ p for 0<p <1.
Exercises
1. Suppose that a random variable X has the Bernoulli
distribution with parameter p = 0.7. (See Definition
3.1.5.) Sketch the c.d.f. of X.
2. Suppose that a random variable X can take only the
values −2, 0, 1, and 4, and that the probabilities of these
values are as follows: Pr(X =−2) = 0.4, Pr(X = 0) = 0.1,
Pr(X = 1) = 0.3, and Pr(X = 4) = 0.2. Sketch the c.d.f. of
X.
3. Suppose that a coin is tossed repeatedly until a head is
obtained for the first time, and let X denote the number
of tosses that are required. Sketch the c.d.f. of X.
4. Suppose that the c.d.f. F of a random variable X is as
sketched in Fig. 3.9. Find each of the following probabilities:
a. Pr(X =−1) b. Pr(X < 0)
c. Pr(X ≤ 0) d. Pr(X = 1)
e. Pr(0<X ≤ 3) f. Pr(0<X <3)
g. Pr(0 ≤ X ≤ 3) h. Pr(1<X ≤ 2)
i. Pr(1≤ X ≤ 2) j. Pr(X > 5)
k. Pr(X ≥ 5) l. Pr(3 ≤ X ≤ 4)
5. Suppose that the c.d.f. of a random variable X is as
follows:
F(x) =
⎧⎪⎨
⎪⎩
0 for x ≤ 0,
1
9x2 for 0 < x ≤ 3,
1 for x >3.
Find and sketch the p.d.f. of X.
3.3 The Cumulative Distribution Function 117
6. Suppose that the c.d.f. of a random variable X is as
follows:
F(x) =
 
ex−3 for x ≤ 3,
1 for x >3.
Find and sketch the p.d.f. of X.
7. Suppose, as in Exercise 7 of Sec. 3.2, that a random
variable X has the uniform distribution on the interval
[−2, 8]. Find and sketch the c.d.f. of X.
8. Suppose that a point in the xy-plane is chosen at random
from the interior of a circle for which the equation is
x2 + y2 = 1; and suppose that the probability that the point
will belong to each region inside the circle is proportional
to the area of that region. Let Z denote a random variable
representing the distance from the center of the circle to
the point. Find and sketch the c.d.f. of Z.
9. Suppose that X has the uniform distribution on the
interval [0, 5] and that the random variable Y is defined
by Y = 0 if X ≤ 1, Y = 5 if X ≥ 3, and Y = X otherwise.
Sketch the c.d.f. of Y .
10. For the c.d.f. in Example 3.3.4, find the quantile function.
11. For the c.d.f. in Exercise 5, find the quantile function.
12. For the c.d.f. in Exercise 6, find the quantile function.
13. Suppose that a broker believes that the change in
value X of a particular investment over the next two
months has the uniform distribution on the interval [−12,
24]. Find the value at risk VaR for two months at probability
level 0.95.
14. Find the quartiles and the median of the binomial
distribution with parameters n = 10 and p = 0.2.
1
0.8
0.6
0.4
 1 1 2 3 4 5
0.2
0 x
F(x)
Figure 3.9 The c.d.f. for Exercise 4.
15. Suppose that X has the p.d.f.
f (x) =
 
2x if 0 < x <1,
0 otherwise.
Find and sketch the c.d.f. or X.
16. Find the quantile function for the distribution in Example
3.3.1.
17. Prove that the quantile function F
−1 of a general random
variableX has the following three properties that are
analogous to properties of the c.d.f.:
a. F
−1 is a nondecreasing function of p for 0<p <1.
b. Let x0 = lim p→0
p>0
F
−1(p) and x1 = lim p→1
p<1
F
−1(p).
Then x0 equals the greatest lower bound on the set
of numbers c such that Pr(X ≤ c) > 0, and x1 equals
the least upper bound on the set of numbers d such
that Pr(X ≥ d) > 0.
c. F
−1 is continuous from the left; that is F
−1(p) =
F
−1(p
−
) for all 0<p <1.
18. Let X be a random variable with quantile function
F
−1. Assume the following three conditions: (i) F
−1(p) =
c for all p in the interval (p0, p1), (ii) either p0 = 0 or
F
−1(p0) < c, and (iii) either p1 = 1 or F
−1(p) > c for p >
p1. Prove that Pr(X = c) = p1 − p0.
19. Let X be a random variable with c.d.f. F and quantile
function F
−1. Let x0 and x1 be as defined in Exercise 17.
(Note that x0 =−∞ and/or x1=∞ are possible.) Prove
that for all x in the open interval (x0, x1), F(x) is the largest
p such that F
−1(p) ≤ x.

::: {#exr-3-3-20}

# Exercise 3.3.20

In Exercise 13 of Sec. 3.2, draw a sketch of the c.d.f. F
of X and find F(10).

:::
