
## Supplementary Exercises {#sec-2-5}

::: {#exr-2-5-1}

# Exercise 2.5.1

1. Suppose that $A$, $B$, and $D$ are any three events such that
Pr(A|D) ≥ Pr(B|D) and Pr(A|Dc) ≥ Pr(B|Dc). Prove that
Pr(A) ≥ Pr(B).

:::

::: {#exr-2-5-2}

# Exercise 2.5.2

2. Suppose that a fair coin is tossed repeatedly and independently
until both a head and a tail have appeared at
least once. (a) Describe the sample space of this experiment.
(b)What is the probability that exactly three tosses
will be required?
3. Suppose that A and B are events such that Pr(A) =
1/3, Pr(B) = 1/5, and Pr(A|B) + Pr(B|A) = 2/3. Evaluate
Pr(Ac ∪ Bc).
4. Suppose thatAand B are independent events such that
Pr(A) = 1/3 and Pr(B) > 0. What is the value of Pr(A ∪
Bc|B)?
5. Suppose that in 10 rolls of a balanced die, the number 6
appeared exactly three times.What is the probability that
the first three rolls each yielded the number 6?
6. Suppose that A, B, and D are events such that A and
B are independent, Pr(A ∩ B ∩ D) = 0.04, Pr(D|A ∩ B) =
0.25, and Pr(B) = 4 Pr(A). Evaluate Pr(A ∪ B).
7. Suppose that the events A, B, and C are mutually independent.
Under what conditions are Ac, Bc, and Cc
mutually independent?
8. Suppose that the events A and B are disjoint and that
each has positive probability. Are A and B independent?
9. Suppose that A, B, and C are three events such that A
and B are disjoint, A and C are independent, and B and
C are independent. Suppose also that 4Pr(A) = 2Pr(B) =
Pr(C) > 0 and Pr(A ∪ B ∪ C) = 5Pr(A). Determine the
value of Pr(A).
10. Suppose that each of two dice is loaded so that when
either die is rolled, the probability that the number k will
appear is 0.1 for k = 1, 2, 5, or 6 and is 0.3 for k = 3 or 4. If
the two loaded dice are rolled independently, what is the
probability that the sum of the two numbers that appear
will be 7?
11. Suppose that there is a probability of 1/50 that you
will win a certain game. If you play the game 50 times,
independently, what is the probability that you will win at
least once?
12. Suppose that a balanced die is rolled three times, and
let Xi denote the number that appears on the ith roll
(i = 1, 2, 3). Evaluate Pr(X1>X2 >X3).
13. Three students A, B, and C are enrolled in the same
class. Suppose that A attends class 30 percent of the time,
B attends class 50 percent of the time, and C attends
class 80 percent of the time. If these students attend class
independently of each other, what is (a) the probability
that at least one of them will be in class on a particular
day and (b) the probability that exactly one of them will
be in class on a particular day?
14. Consider theWorld Series of baseball, as described in
Exercise 16 of Sec. 2.2. If there is probability p that team
A will win any particular game, what is the probability
2.5 Supplementary Exercises 91
that it will be necessary to play seven games in order to
determine the winner of the Series?
15. Suppose that three red balls and three white balls are
thrown at random into three boxes and and that all throws
are independent. What is the probability that each box
contains one red ball and one white ball?
16. If five balls are thrown at random into n boxes, and all
throws are independent, what is the probability that no
box contains more than two balls?
17. Bus tickets in a certain city contain four numbers, U,
V , W, and X. Each of these numbers is equally likely to
be any of the 10 digits 0, 1, . . . , 9, and the four numbers
are chosen independently.Abus rider is said to be lucky if
U + V =W + X.What proportion of the riders are lucky?
18. A certain group has eight members. In January, three
members are selected at random to serve on a committee.
In February, four members are selected at random
and independently of the first selection to serve on another
committee. In March, five members are selected at
random and independently of the previous two selections
to serve on a third committee. Determine the probability
that each of the eight members serves on at least one of
the three committees.
19. For the conditions of Exercise 18, determine the probability
that two particular members A and B will serve
together on at least one of the three committees.
20. Suppose that two players A and B take turns rolling a
pair of balanced dice and that the winner is the first player
who obtains the sum of 7 on a given roll of the two dice.
If A rolls first, what is the probability that B will win?
21. Three players A, B, and C take turns tossing a fair
coin. Suppose that A tosses the coin first, B tosses second,
and C tosses third; and suppose that this cycle is repeated
indefinitely until someone wins by being the first player
to obtain a head. Determine the probability that each of
three players will win.
22. Suppose that a balanced die is rolled repeatedly until
the same number appears on two successive rolls, and let
X denote the number of rolls that are required. Determine
the value of Pr(X = x), for x = 2, 3, . . . .
23. Suppose that 80 percent of all statisticians are shy,
whereas only 15 percent of all economists are shy. Suppose
also that 90 percent of the people at a large gathering are
economists and the other 10 percent are statisticians. If
you meet a shy person at random at the gathering, what is
the probability that the person is a statistician?
24. Dreamboat cars are produced at three different factories
A, B, and C. Factory A produces 20 percent of the
total output of Dreamboats, B produces 50 percent, and
C produces 30 percent. However, 5 percent of the cars
produced at A are lemons, 2 percent of those produced
at B are lemons, and 10 percent of those produced at C
are lemons. If you buy a Dreamboat and it turns out to be
a lemon, what is the probability that it was produced at
factory A?
25. Suppose that 30 percent of the bottles produced in
a certain plant are defective. If a bottle is defective, the
probability is 0.9 that an inspector will notice it and remove
it from the filling line. If a bottle is not defective,
the probability is 0.2 that the inspector will think that it is
defective and remove it from the filling line.
a. If a bottle is removed from the filling line, what is the
probability that it is defective?
b. If a customer buys a bottle that has not been removed
from the filling line, what is the probability that it is
defective?
26. Suppose that a fair coin is tossed until a head is obtained
and that this entire experiment is then performed
independently a second time.What is the probability that
the second experiment requires more tosses than the first
experiment?
27. Suppose that a family has exactly n children (n ≥ 2).
Assume that the probability that any child will be a girl
is 1/2 and that all births are independent. Given that the
family has at least one girl, determine the probability that
the family has at least one boy.
28. Suppose that a fair coin is tossed independently n
times. Determine the probability of obtaining exactly n −
1 heads, given (a) that at least n − 2 heads are obtained
and (b) that heads are obtained on the first n − 2 tosses.
29. Suppose that 13 cards are selected at random from a
regular deck of 52 playing cards.
a. If it is known that at least one ace has been selected,
what is the probability that at least two aces have
been selected?
b. If it is known that the ace of hearts has been selected,
what is the probability that at least two aces have
been selected?
30. Suppose that n letters are placed at random in n envelopes,
as in the matching problem of Sec. 1.10, and let qn
denote the probability that no letter is placed in the correct
envelope. Show that the probability that exactly one
letter is placed in the correct envelope is qn−1.
31. Consider again the conditions of Exercise 30. Show
that the probability that exactly two letters are placed in
the correct envelopes is (1/2)qn−2.
32. Consider again the conditions of Exercise 7 of Sec. 2.2.
If exactly one of the two students A and B is in class on a
given day, what is the probability that it is A?
33. Consider again the conditions of Exercise 2 of Sec.
1.10. If a family selected at random from the city
92 Chapter 2 Conditional Probability
subscribes to exactly one of the three newspapers A, B,
and C, what is the probability that it is A?
34. Three prisoners A, B, and C on death row know that
exactly two of them are going to be executed, but they do
not know which two. Prisoner A knows that the jailer will
not tell him whether or not he is going to be executed. He
therefore asks the jailer to tell him the name of one prisoner
other than A himself who will be executed. The jailer
responds that B will be executed. Upon receiving this response,
Prisoner A reasons as follows: Before he spoke to
the jailer, the probability was 2/3 that he would be one of
the two prisoners executed. After speaking to the jailer,
he knows that either he or prisoner C will be the other
one to be executed. Hence, the probability that he will be
executed is now only 1/2. Thus, merely by asking the jailer
his question, the prisoner reduced the probability that he
would be executed from 2/3 to 1/2, because he could go
through exactly this same reasoning regardless of which
answer the jailer gave. Discuss what is wrong with prisoner
A’s reasoning.
35. Suppose that each of two gamblers A and B has an
initial fortune of 50 dollars, and that there is probability
p that gambler A will win on any single play of a game
against gambler B. Also, suppose either that one gambler
can win one dollar from the other on each play of the game
or that they can double the stakes and one can win two
dollars from the other on each play of the game. Under
which of these two conditions does A have the greater
probability of winning the initial fortune ofB before losing
her own for each of the following conditions: (a) p <1/2;
(b) p >1/2; (c) p = 1/2?
36. A sequence of n job candidates is prepared to interview
for a job. We would like to hire the best candidate,
but we have no information to distinguish the candidates
before we interview them.We assume that the best candidate
is equally likely to be each of the n candidates in the
sequence before the interviews start. After the interviews
start, we are able to rank those candidates we have seen,
but we have no information about where the remaining
candidates rank relative to those we have seen. After each
interview, it is required that either we hire the current candidate
immediately and stop the interviews, or we must let
the current candidate go and we never can call them back.
We choose to interview as follows: We select a number
0 ≤ r < n and we interview the first r candidates without
any intention of hiring them. Starting with the next candidate
r + 1, we continue interviewing until the current
candidate is the best we have seen so far. We then stop
and hire the current candidate. If none of the candidates
from r + 1 to n is the best, we just hire candidate n. We
would like to compute the probability that we hire the best
candidate and we would like to choose r to make this probability
as large as possible. Let A be the event that we hire
the best candidate, and let Bi be the event that the best
candidate is in position i in the sequence of interviews.
a. Leti >r. Find the probability that the candidate who
is relatively the best among the first i interviewed
appears in the first r interviews.
b. Prove that Pr(A|Bi) = 0 for i ≤ r and Pr(A|Bi) =
r/(i − 1) for i > r.
c. For fixed r, let pr be the probability of A using that
value of r. Prove that pr
= (r/n)
 n
i=r+1(i − 1)
−1.
d. Let qr
= pr
− pr−1 for r = 1, . . . , n − 1, and prove
that qr is a strictly decreasing function of r.
e. Show that a value of r that maximizes pr is the last r
such that qr > 0. (Hint: Write pr
= p0 + q1 + . . . + qr
for r > 0.)
f. For n = 10, find the value of r that maximizes pr , and
find the corresponding pr value.
